// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella.Absyn;

import java.io.Serializable;

public abstract class Annotation implements Serializable {
  public abstract <R,A> R accept(Annotation.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(InlineAnnotation p, A arg);

  }

}
