// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella.Absyn;

import java.io.Serializable;

public abstract class Decl implements Serializable {
  public abstract <R,A> R accept(Decl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(DeclFun p, A arg);
    public R visit(DeclFunGeneric p, A arg);
    public R visit(DeclTypeAlias p, A arg);
    public R visit(DeclExceptionType p, A arg);
    public R visit(DeclExceptionVariant p, A arg);

  }

}
