// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella.Absyn;

public class NoExprData  extends ExprData {
  public int line_num, col_num, offset;
  public NoExprData() { }

  public <R,A> R accept(ExprData.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof NoExprData) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
