// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella.Absyn;

import java.io.Serializable;

public abstract class Pattern implements Serializable {
  public abstract <R,A> R accept(Pattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(PatternCastAs p, A arg);
    public R visit(PatternAsc p, A arg);
    public R visit(PatternVariant p, A arg);
    public R visit(PatternInl p, A arg);
    public R visit(PatternInr p, A arg);
    public R visit(PatternTuple p, A arg);
    public R visit(PatternRecord p, A arg);
    public R visit(PatternList p, A arg);
    public R visit(PatternCons p, A arg);
    public R visit(PatternFalse p, A arg);
    public R visit(PatternTrue p, A arg);
    public R visit(PatternUnit p, A arg);
    public R visit(PatternInt p, A arg);
    public R visit(PatternSucc p, A arg);
    public R visit(PatternVar p, A arg);

  }

}
