// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella.Absyn;

import java.io.Serializable;

public abstract class ReturnType implements Serializable {
  public abstract <R,A> R accept(ReturnType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(NoReturnType p, A arg);
    public R visit(SomeReturnType p, A arg);

  }

}
