// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella;

import org.syntax.stella.Absyn.Pattern;
import org.syntax.stella.Absyn.PatternCons;

import java.util.LinkedList;

public class AbsynDef {

  public static <B,A extends LinkedList<? super B>> A cons(B x, A xs) {
    xs.addFirst(x);
    return xs;
  }

  public static Pattern patternCons(Pattern h, Pattern t) {
    return new PatternCons(h, t);
  }

}
