// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella;

import org.syntax.stella.Absyn.Annotation;
import org.syntax.stella.Absyn.Binding;
import org.syntax.stella.Absyn.Decl;
import org.syntax.stella.Absyn.Expr;
import org.syntax.stella.Absyn.ExprData;
import org.syntax.stella.Absyn.Extension;
import org.syntax.stella.Absyn.LabelledPattern;
import org.syntax.stella.Absyn.LanguageDecl;
import org.syntax.stella.Absyn.LocalDecl;
import org.syntax.stella.Absyn.MatchCase;
import org.syntax.stella.Absyn.OptionalTyping;
import org.syntax.stella.Absyn.ParamDecl;
import org.syntax.stella.Absyn.Pattern;
import org.syntax.stella.Absyn.PatternBinding;
import org.syntax.stella.Absyn.PatternData;
import org.syntax.stella.Absyn.Program;
import org.syntax.stella.Absyn.RecordFieldType;
import org.syntax.stella.Absyn.ReturnType;
import org.syntax.stella.Absyn.ThrowType;
import org.syntax.stella.Absyn.Type;
import org.syntax.stella.Absyn.Typing;
import org.syntax.stella.Absyn.VariantFieldType;

/** All Visitor */

public interface AllVisitor<R,A> extends
  Program.Visitor<R,A>,
  LanguageDecl.Visitor<R,A>,
  Extension.Visitor<R,A>,
  Decl.Visitor<R,A>,
  LocalDecl.Visitor<R,A>,
  Annotation.Visitor<R,A>,
  ParamDecl.Visitor<R,A>,
  ReturnType.Visitor<R,A>,
  ThrowType.Visitor<R,A>,
  Type.Visitor<R,A>,
  MatchCase.Visitor<R,A>,
  OptionalTyping.Visitor<R,A>,
  PatternData.Visitor<R,A>,
  ExprData.Visitor<R,A>,
  Pattern.Visitor<R,A>,
  LabelledPattern.Visitor<R,A>,
  Binding.Visitor<R,A>,
  Expr.Visitor<R,A>,
  PatternBinding.Visitor<R,A>,
  VariantFieldType.Visitor<R,A>,
  RecordFieldType.Visitor<R,A>,
  Typing.Visitor<R,A>
{}
