// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella;

import org.syntax.stella.Absyn.ABinding;
import org.syntax.stella.Absyn.ALabelledPattern;
import org.syntax.stella.Absyn.ALocalDecl;
import org.syntax.stella.Absyn.AMatchCase;
import org.syntax.stella.Absyn.AParamDecl;
import org.syntax.stella.Absyn.APatternBinding;
import org.syntax.stella.Absyn.AProgram;
import org.syntax.stella.Absyn.ARecordFieldType;
import org.syntax.stella.Absyn.ATyping;
import org.syntax.stella.Absyn.AVariantFieldType;
import org.syntax.stella.Absyn.Abstraction;
import org.syntax.stella.Absyn.Add;
import org.syntax.stella.Absyn.AnExtension;
import org.syntax.stella.Absyn.Annotation;
import org.syntax.stella.Absyn.Application;
import org.syntax.stella.Absyn.Assign;
import org.syntax.stella.Absyn.Binding;
import org.syntax.stella.Absyn.ConsList;
import org.syntax.stella.Absyn.ConstFalse;
import org.syntax.stella.Absyn.ConstInt;
import org.syntax.stella.Absyn.ConstMemory;
import org.syntax.stella.Absyn.ConstTrue;
import org.syntax.stella.Absyn.ConstUnit;
import org.syntax.stella.Absyn.Decl;
import org.syntax.stella.Absyn.DeclExceptionType;
import org.syntax.stella.Absyn.DeclExceptionVariant;
import org.syntax.stella.Absyn.DeclFun;
import org.syntax.stella.Absyn.DeclFunGeneric;
import org.syntax.stella.Absyn.DeclTypeAlias;
import org.syntax.stella.Absyn.Deref;
import org.syntax.stella.Absyn.Divide;
import org.syntax.stella.Absyn.DotRecord;
import org.syntax.stella.Absyn.DotTuple;
import org.syntax.stella.Absyn.Equal;
import org.syntax.stella.Absyn.Expr;
import org.syntax.stella.Absyn.ExprData;
import org.syntax.stella.Absyn.Extension;
import org.syntax.stella.Absyn.Fix;
import org.syntax.stella.Absyn.Fold;
import org.syntax.stella.Absyn.GreaterThan;
import org.syntax.stella.Absyn.GreaterThanOrEqual;
import org.syntax.stella.Absyn.Head;
import org.syntax.stella.Absyn.If;
import org.syntax.stella.Absyn.Inl;
import org.syntax.stella.Absyn.InlineAnnotation;
import org.syntax.stella.Absyn.Inr;
import org.syntax.stella.Absyn.IsEmpty;
import org.syntax.stella.Absyn.IsZero;
import org.syntax.stella.Absyn.LabelledPattern;
import org.syntax.stella.Absyn.LanguageCore;
import org.syntax.stella.Absyn.LanguageDecl;
import org.syntax.stella.Absyn.LessThan;
import org.syntax.stella.Absyn.LessThanOrEqual;
import org.syntax.stella.Absyn.Let;
import org.syntax.stella.Absyn.LetRec;
import org.syntax.stella.Absyn.List;
import org.syntax.stella.Absyn.ListAnnotation;
import org.syntax.stella.Absyn.ListBinding;
import org.syntax.stella.Absyn.ListDecl;
import org.syntax.stella.Absyn.ListExpr;
import org.syntax.stella.Absyn.ListExtension;
import org.syntax.stella.Absyn.ListExtensionName;
import org.syntax.stella.Absyn.ListLabelledPattern;
import org.syntax.stella.Absyn.ListMatchCase;
import org.syntax.stella.Absyn.ListParamDecl;
import org.syntax.stella.Absyn.ListPattern;
import org.syntax.stella.Absyn.ListPatternBinding;
import org.syntax.stella.Absyn.ListRecordFieldType;
import org.syntax.stella.Absyn.ListStellaIdent;
import org.syntax.stella.Absyn.ListType;
import org.syntax.stella.Absyn.ListVariantFieldType;
import org.syntax.stella.Absyn.LocalDecl;
import org.syntax.stella.Absyn.LogicAnd;
import org.syntax.stella.Absyn.LogicNot;
import org.syntax.stella.Absyn.LogicOr;
import org.syntax.stella.Absyn.Match;
import org.syntax.stella.Absyn.MatchCase;
import org.syntax.stella.Absyn.Multiply;
import org.syntax.stella.Absyn.NatRec;
import org.syntax.stella.Absyn.NoExprData;
import org.syntax.stella.Absyn.NoPatternData;
import org.syntax.stella.Absyn.NoReturnType;
import org.syntax.stella.Absyn.NoThrowType;
import org.syntax.stella.Absyn.NoTyping;
import org.syntax.stella.Absyn.NotEqual;
import org.syntax.stella.Absyn.OptionalTyping;
import org.syntax.stella.Absyn.Panic;
import org.syntax.stella.Absyn.ParamDecl;
import org.syntax.stella.Absyn.Pattern;
import org.syntax.stella.Absyn.PatternAsc;
import org.syntax.stella.Absyn.PatternBinding;
import org.syntax.stella.Absyn.PatternCastAs;
import org.syntax.stella.Absyn.PatternCons;
import org.syntax.stella.Absyn.PatternData;
import org.syntax.stella.Absyn.PatternFalse;
import org.syntax.stella.Absyn.PatternInl;
import org.syntax.stella.Absyn.PatternInr;
import org.syntax.stella.Absyn.PatternInt;
import org.syntax.stella.Absyn.PatternList;
import org.syntax.stella.Absyn.PatternRecord;
import org.syntax.stella.Absyn.PatternSucc;
import org.syntax.stella.Absyn.PatternTrue;
import org.syntax.stella.Absyn.PatternTuple;
import org.syntax.stella.Absyn.PatternUnit;
import org.syntax.stella.Absyn.PatternVar;
import org.syntax.stella.Absyn.PatternVariant;
import org.syntax.stella.Absyn.Pred;
import org.syntax.stella.Absyn.Program;
import org.syntax.stella.Absyn.Record;
import org.syntax.stella.Absyn.RecordFieldType;
import org.syntax.stella.Absyn.Ref;
import org.syntax.stella.Absyn.ReturnType;
import org.syntax.stella.Absyn.Sequence;
import org.syntax.stella.Absyn.SomeExprData;
import org.syntax.stella.Absyn.SomePatternData;
import org.syntax.stella.Absyn.SomeReturnType;
import org.syntax.stella.Absyn.SomeThrowType;
import org.syntax.stella.Absyn.SomeTyping;
import org.syntax.stella.Absyn.Subtract;
import org.syntax.stella.Absyn.Succ;
import org.syntax.stella.Absyn.Tail;
import org.syntax.stella.Absyn.Throw;
import org.syntax.stella.Absyn.ThrowType;
import org.syntax.stella.Absyn.TryCastAs;
import org.syntax.stella.Absyn.TryCatch;
import org.syntax.stella.Absyn.TryWith;
import org.syntax.stella.Absyn.Tuple;
import org.syntax.stella.Absyn.Type;
import org.syntax.stella.Absyn.TypeAbstraction;
import org.syntax.stella.Absyn.TypeApplication;
import org.syntax.stella.Absyn.TypeAsc;
import org.syntax.stella.Absyn.TypeAuto;
import org.syntax.stella.Absyn.TypeBool;
import org.syntax.stella.Absyn.TypeBottom;
import org.syntax.stella.Absyn.TypeCast;
import org.syntax.stella.Absyn.TypeForAll;
import org.syntax.stella.Absyn.TypeFun;
import org.syntax.stella.Absyn.TypeList;
import org.syntax.stella.Absyn.TypeNat;
import org.syntax.stella.Absyn.TypeRec;
import org.syntax.stella.Absyn.TypeRecord;
import org.syntax.stella.Absyn.TypeRef;
import org.syntax.stella.Absyn.TypeSum;
import org.syntax.stella.Absyn.TypeTop;
import org.syntax.stella.Absyn.TypeTuple;
import org.syntax.stella.Absyn.TypeUnit;
import org.syntax.stella.Absyn.TypeVar;
import org.syntax.stella.Absyn.TypeVariant;
import org.syntax.stella.Absyn.Typing;
import org.syntax.stella.Absyn.Unfold;
import org.syntax.stella.Absyn.Var;
import org.syntax.stella.Absyn.Variant;
import org.syntax.stella.Absyn.VariantFieldType;

/** Composition Visitor
*/

public class ComposVisitor<A> implements
  Program.Visitor<Program,A>,
  LanguageDecl.Visitor<LanguageDecl,A>,
  Extension.Visitor<Extension,A>,
  Decl.Visitor<Decl,A>,
  LocalDecl.Visitor<LocalDecl,A>,
  Annotation.Visitor<Annotation,A>,
  ParamDecl.Visitor<ParamDecl,A>,
  ReturnType.Visitor<ReturnType,A>,
  ThrowType.Visitor<ThrowType,A>,
  Type.Visitor<Type,A>,
  MatchCase.Visitor<MatchCase,A>,
  OptionalTyping.Visitor<OptionalTyping,A>,
  PatternData.Visitor<PatternData,A>,
  ExprData.Visitor<ExprData,A>,
  Pattern.Visitor<Pattern,A>,
  LabelledPattern.Visitor<LabelledPattern,A>,
  Binding.Visitor<Binding,A>,
  Expr.Visitor<Expr,A>,
  PatternBinding.Visitor<PatternBinding,A>,
  VariantFieldType.Visitor<VariantFieldType,A>,
  RecordFieldType.Visitor<RecordFieldType,A>,
  Typing.Visitor<Typing,A>
{
    /* Program */
    public Program visit(AProgram p, A arg)
    {
      LanguageDecl languagedecl_ = p.languagedecl_.accept(this, arg);
      ListExtension listextension_ = new ListExtension();
      for (Extension x : p.listextension_)
      {
        listextension_.add(x.accept(this,arg));
      }
      ListDecl listdecl_ = new ListDecl();
      for (Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      return new AProgram(languagedecl_, listextension_, listdecl_);
    }

    /* LanguageDecl */
    public LanguageDecl visit(LanguageCore p, A arg)
    {
      return new LanguageCore();
    }

    /* Extension */
    public Extension visit(AnExtension p, A arg)
    {
      ListExtensionName listextensionname_ = p.listextensionname_;
      return new AnExtension(listextensionname_);
    }

    /* Decl */
    public Decl visit(DeclFun p, A arg)
    {
      ListAnnotation listannotation_ = new ListAnnotation();
      for (Annotation x : p.listannotation_)
      {
        listannotation_.add(x.accept(this,arg));
      }
      String stellaident_ = p.stellaident_;
      ListParamDecl listparamdecl_ = new ListParamDecl();
      for (ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      ReturnType returntype_ = p.returntype_.accept(this, arg);
      ThrowType throwtype_ = p.throwtype_.accept(this, arg);
      ListDecl listdecl_ = new ListDecl();
      for (Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      Expr expr_ = p.expr_.accept(this, arg);
      return new DeclFun(listannotation_, stellaident_, listparamdecl_, returntype_, throwtype_, listdecl_, expr_);
    }
    public Decl visit(DeclFunGeneric p, A arg)
    {
      ListAnnotation listannotation_ = new ListAnnotation();
      for (Annotation x : p.listannotation_)
      {
        listannotation_.add(x.accept(this,arg));
      }
      String stellaident_ = p.stellaident_;
      ListStellaIdent liststellaident_ = p.liststellaident_;
      ListParamDecl listparamdecl_ = new ListParamDecl();
      for (ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      ReturnType returntype_ = p.returntype_.accept(this, arg);
      ThrowType throwtype_ = p.throwtype_.accept(this, arg);
      ListDecl listdecl_ = new ListDecl();
      for (Decl x : p.listdecl_)
      {
        listdecl_.add(x.accept(this,arg));
      }
      Expr expr_ = p.expr_.accept(this, arg);
      return new DeclFunGeneric(listannotation_, stellaident_, liststellaident_, listparamdecl_, returntype_, throwtype_, listdecl_, expr_);
    }
    public Decl visit(DeclTypeAlias p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Type type_ = p.type_.accept(this, arg);
      return new DeclTypeAlias(stellaident_, type_);
    }
    public Decl visit(DeclExceptionType p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      return new DeclExceptionType(type_);
    }
    public Decl visit(DeclExceptionVariant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Type type_ = p.type_.accept(this, arg);
      return new DeclExceptionVariant(stellaident_, type_);
    }

    /* LocalDecl */
    public LocalDecl visit(ALocalDecl p, A arg)
    {
      Decl decl_ = p.decl_.accept(this, arg);
      return new ALocalDecl(decl_);
    }

    /* Annotation */
    public Annotation visit(InlineAnnotation p, A arg)
    {
      return new InlineAnnotation();
    }

    /* ParamDecl */
    public ParamDecl visit(AParamDecl p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Type type_ = p.type_.accept(this, arg);
      return new AParamDecl(stellaident_, type_);
    }

    /* ReturnType */
    public ReturnType visit(NoReturnType p, A arg)
    {
      return new NoReturnType();
    }
    public ReturnType visit(SomeReturnType p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      return new SomeReturnType(type_);
    }

    /* ThrowType */
    public ThrowType visit(NoThrowType p, A arg)
    {
      return new NoThrowType();
    }
    public ThrowType visit(SomeThrowType p, A arg)
    {
      ListType listtype_ = new ListType();
      for (Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new SomeThrowType(listtype_);
    }

    /* Type */
    public Type visit(TypeAuto p, A arg)
    {
      return new TypeAuto();
    }
    public Type visit(TypeFun p, A arg)
    {
      ListType listtype_ = new ListType();
      for (Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      Type type_ = p.type_.accept(this, arg);
      return new TypeFun(listtype_, type_);
    }
    public Type visit(TypeForAll p, A arg)
    {
      ListStellaIdent liststellaident_ = p.liststellaident_;
      Type type_ = p.type_.accept(this, arg);
      return new TypeForAll(liststellaident_, type_);
    }
    public Type visit(TypeRec p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Type type_ = p.type_.accept(this, arg);
      return new TypeRec(stellaident_, type_);
    }
    public Type visit(TypeSum p, A arg)
    {
      Type type_1 = p.type_1.accept(this, arg);
      Type type_2 = p.type_2.accept(this, arg);
      return new TypeSum(type_1, type_2);
    }
    public Type visit(TypeTuple p, A arg)
    {
      ListType listtype_ = new ListType();
      for (Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new TypeTuple(listtype_);
    }
    public Type visit(TypeRecord p, A arg)
    {
      ListRecordFieldType listrecordfieldtype_ = new ListRecordFieldType();
      for (RecordFieldType x : p.listrecordfieldtype_)
      {
        listrecordfieldtype_.add(x.accept(this,arg));
      }
      return new TypeRecord(listrecordfieldtype_);
    }
    public Type visit(TypeVariant p, A arg)
    {
      ListVariantFieldType listvariantfieldtype_ = new ListVariantFieldType();
      for (VariantFieldType x : p.listvariantfieldtype_)
      {
        listvariantfieldtype_.add(x.accept(this,arg));
      }
      return new TypeVariant(listvariantfieldtype_);
    }
    public Type visit(TypeList p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      return new TypeList(type_);
    }
    public Type visit(TypeBool p, A arg)
    {
      return new TypeBool();
    }
    public Type visit(TypeNat p, A arg)
    {
      return new TypeNat();
    }
    public Type visit(TypeUnit p, A arg)
    {
      return new TypeUnit();
    }
    public Type visit(TypeTop p, A arg)
    {
      return new TypeTop();
    }
    public Type visit(TypeBottom p, A arg)
    {
      return new TypeBottom();
    }
    public Type visit(TypeRef p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      return new TypeRef(type_);
    }
    public Type visit(TypeVar p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new TypeVar(stellaident_);
    }

    /* MatchCase */
    public MatchCase visit(AMatchCase p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      Expr expr_ = p.expr_.accept(this, arg);
      return new AMatchCase(pattern_, expr_);
    }

    /* OptionalTyping */
    public OptionalTyping visit(NoTyping p, A arg)
    {
      return new NoTyping();
    }
    public OptionalTyping visit(SomeTyping p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      return new SomeTyping(type_);
    }

    /* PatternData */
    public PatternData visit(NoPatternData p, A arg)
    {
      return new NoPatternData();
    }
    public PatternData visit(SomePatternData p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      return new SomePatternData(pattern_);
    }

    /* ExprData */
    public ExprData visit(NoExprData p, A arg)
    {
      return new NoExprData();
    }
    public ExprData visit(SomeExprData p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new SomeExprData(expr_);
    }

    /* Pattern */
    public Pattern visit(PatternCastAs p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      Type type_ = p.type_.accept(this, arg);
      return new PatternCastAs(pattern_, type_);
    }
    public Pattern visit(PatternAsc p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      Type type_ = p.type_.accept(this, arg);
      return new PatternAsc(pattern_, type_);
    }
    public Pattern visit(PatternVariant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      PatternData patterndata_ = p.patterndata_.accept(this, arg);
      return new PatternVariant(stellaident_, patterndata_);
    }
    public Pattern visit(PatternInl p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      return new PatternInl(pattern_);
    }
    public Pattern visit(PatternInr p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      return new PatternInr(pattern_);
    }
    public Pattern visit(PatternTuple p, A arg)
    {
      ListPattern listpattern_ = new ListPattern();
      for (Pattern x : p.listpattern_)
      {
        listpattern_.add(x.accept(this,arg));
      }
      return new PatternTuple(listpattern_);
    }
    public Pattern visit(PatternRecord p, A arg)
    {
      ListLabelledPattern listlabelledpattern_ = new ListLabelledPattern();
      for (LabelledPattern x : p.listlabelledpattern_)
      {
        listlabelledpattern_.add(x.accept(this,arg));
      }
      return new PatternRecord(listlabelledpattern_);
    }
    public Pattern visit(PatternList p, A arg)
    {
      ListPattern listpattern_ = new ListPattern();
      for (Pattern x : p.listpattern_)
      {
        listpattern_.add(x.accept(this,arg));
      }
      return new PatternList(listpattern_);
    }
    public Pattern visit(PatternCons p, A arg)
    {
      Pattern pattern_1 = p.pattern_1.accept(this, arg);
      Pattern pattern_2 = p.pattern_2.accept(this, arg);
      return new PatternCons(pattern_1, pattern_2);
    }
    public Pattern visit(PatternFalse p, A arg)
    {
      return new PatternFalse();
    }
    public Pattern visit(PatternTrue p, A arg)
    {
      return new PatternTrue();
    }
    public Pattern visit(PatternUnit p, A arg)
    {
      return new PatternUnit();
    }
    public Pattern visit(PatternInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new PatternInt(integer_);
    }
    public Pattern visit(PatternSucc p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      return new PatternSucc(pattern_);
    }
    public Pattern visit(PatternVar p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new PatternVar(stellaident_);
    }

    /* LabelledPattern */
    public LabelledPattern visit(ALabelledPattern p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Pattern pattern_ = p.pattern_.accept(this, arg);
      return new ALabelledPattern(stellaident_, pattern_);
    }

    /* Binding */
    public Binding visit(ABinding p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Expr expr_ = p.expr_.accept(this, arg);
      return new ABinding(stellaident_, expr_);
    }

    /* Expr */
    public Expr visit(Sequence p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Sequence(expr_1, expr_2);
    }
    public Expr visit(Let p, A arg)
    {
      ListPatternBinding listpatternbinding_ = new ListPatternBinding();
      for (PatternBinding x : p.listpatternbinding_)
      {
        listpatternbinding_.add(x.accept(this,arg));
      }
      Expr expr_ = p.expr_.accept(this, arg);
      return new Let(listpatternbinding_, expr_);
    }
    public Expr visit(LetRec p, A arg)
    {
      ListPatternBinding listpatternbinding_ = new ListPatternBinding();
      for (PatternBinding x : p.listpatternbinding_)
      {
        listpatternbinding_.add(x.accept(this,arg));
      }
      Expr expr_ = p.expr_.accept(this, arg);
      return new LetRec(listpatternbinding_, expr_);
    }
    public Expr visit(TypeAbstraction p, A arg)
    {
      ListStellaIdent liststellaident_ = p.liststellaident_;
      Expr expr_ = p.expr_.accept(this, arg);
      return new TypeAbstraction(liststellaident_, expr_);
    }
    public Expr visit(Assign p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Assign(expr_1, expr_2);
    }
    public Expr visit(If p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      Expr expr_3 = p.expr_3.accept(this, arg);
      return new If(expr_1, expr_2, expr_3);
    }
    public Expr visit(LessThan p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new LessThan(expr_1, expr_2);
    }
    public Expr visit(LessThanOrEqual p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new LessThanOrEqual(expr_1, expr_2);
    }
    public Expr visit(GreaterThan p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new GreaterThan(expr_1, expr_2);
    }
    public Expr visit(GreaterThanOrEqual p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new GreaterThanOrEqual(expr_1, expr_2);
    }
    public Expr visit(Equal p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Equal(expr_1, expr_2);
    }
    public Expr visit(NotEqual p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new NotEqual(expr_1, expr_2);
    }
    public Expr visit(TypeAsc p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      Type type_ = p.type_.accept(this, arg);
      return new TypeAsc(expr_, type_);
    }
    public Expr visit(TypeCast p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      Type type_ = p.type_.accept(this, arg);
      return new TypeCast(expr_, type_);
    }
    public Expr visit(Abstraction p, A arg)
    {
      ListParamDecl listparamdecl_ = new ListParamDecl();
      for (ParamDecl x : p.listparamdecl_)
      {
        listparamdecl_.add(x.accept(this,arg));
      }
      Expr expr_ = p.expr_.accept(this, arg);
      return new Abstraction(listparamdecl_, expr_);
    }
    public Expr visit(Variant p, A arg)
    {
      String stellaident_ = p.stellaident_;
      ExprData exprdata_ = p.exprdata_.accept(this, arg);
      return new Variant(stellaident_, exprdata_);
    }
    public Expr visit(Match p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      ListMatchCase listmatchcase_ = new ListMatchCase();
      for (MatchCase x : p.listmatchcase_)
      {
        listmatchcase_.add(x.accept(this,arg));
      }
      return new Match(expr_, listmatchcase_);
    }
    public Expr visit(List p, A arg)
    {
      ListExpr listexpr_ = new ListExpr();
      for (Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new List(listexpr_);
    }
    public Expr visit(Add p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Add(expr_1, expr_2);
    }
    public Expr visit(Subtract p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Subtract(expr_1, expr_2);
    }
    public Expr visit(LogicOr p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new LogicOr(expr_1, expr_2);
    }
    public Expr visit(Multiply p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Multiply(expr_1, expr_2);
    }
    public Expr visit(Divide p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new Divide(expr_1, expr_2);
    }
    public Expr visit(LogicAnd p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new LogicAnd(expr_1, expr_2);
    }
    public Expr visit(Ref p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Ref(expr_);
    }
    public Expr visit(Deref p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Deref(expr_);
    }
    public Expr visit(Application p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      ListExpr listexpr_ = new ListExpr();
      for (Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new Application(expr_, listexpr_);
    }
    public Expr visit(TypeApplication p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      ListType listtype_ = new ListType();
      for (Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new TypeApplication(expr_, listtype_);
    }
    public Expr visit(DotRecord p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      String stellaident_ = p.stellaident_;
      return new DotRecord(expr_, stellaident_);
    }
    public Expr visit(DotTuple p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      Integer integer_ = p.integer_;
      return new DotTuple(expr_, integer_);
    }
    public Expr visit(Tuple p, A arg)
    {
      ListExpr listexpr_ = new ListExpr();
      for (Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new Tuple(listexpr_);
    }
    public Expr visit(Record p, A arg)
    {
      ListBinding listbinding_ = new ListBinding();
      for (Binding x : p.listbinding_)
      {
        listbinding_.add(x.accept(this,arg));
      }
      return new Record(listbinding_);
    }
    public Expr visit(ConsList p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new ConsList(expr_1, expr_2);
    }
    public Expr visit(Head p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Head(expr_);
    }
    public Expr visit(IsEmpty p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new IsEmpty(expr_);
    }
    public Expr visit(Tail p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Tail(expr_);
    }
    public Expr visit(Panic p, A arg)
    {
      return new Panic();
    }
    public Expr visit(Throw p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Throw(expr_);
    }
    public Expr visit(TryCatch p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Pattern pattern_ = p.pattern_.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new TryCatch(expr_1, pattern_, expr_2);
    }
    public Expr visit(TryWith p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      return new TryWith(expr_1, expr_2);
    }
    public Expr visit(TryCastAs p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Type type_ = p.type_.accept(this, arg);
      Pattern pattern_ = p.pattern_.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      Expr expr_3 = p.expr_3.accept(this, arg);
      return new TryCastAs(expr_1, type_, pattern_, expr_2, expr_3);
    }
    public Expr visit(Inl p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Inl(expr_);
    }
    public Expr visit(Inr p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Inr(expr_);
    }
    public Expr visit(Succ p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Succ(expr_);
    }
    public Expr visit(LogicNot p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new LogicNot(expr_);
    }
    public Expr visit(Pred p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Pred(expr_);
    }
    public Expr visit(IsZero p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new IsZero(expr_);
    }
    public Expr visit(Fix p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      return new Fix(expr_);
    }
    public Expr visit(NatRec p, A arg)
    {
      Expr expr_1 = p.expr_1.accept(this, arg);
      Expr expr_2 = p.expr_2.accept(this, arg);
      Expr expr_3 = p.expr_3.accept(this, arg);
      return new NatRec(expr_1, expr_2, expr_3);
    }
    public Expr visit(Fold p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      Expr expr_ = p.expr_.accept(this, arg);
      return new Fold(type_, expr_);
    }
    public Expr visit(Unfold p, A arg)
    {
      Type type_ = p.type_.accept(this, arg);
      Expr expr_ = p.expr_.accept(this, arg);
      return new Unfold(type_, expr_);
    }
    public Expr visit(ConstTrue p, A arg)
    {
      return new ConstTrue();
    }
    public Expr visit(ConstFalse p, A arg)
    {
      return new ConstFalse();
    }
    public Expr visit(ConstUnit p, A arg)
    {
      return new ConstUnit();
    }
    public Expr visit(ConstInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new ConstInt(integer_);
    }
    public Expr visit(ConstMemory p, A arg)
    {
      String memoryaddress_ = p.memoryaddress_;
      return new ConstMemory(memoryaddress_);
    }
    public Expr visit(Var p, A arg)
    {
      String stellaident_ = p.stellaident_;
      return new Var(stellaident_);
    }

    /* PatternBinding */
    public PatternBinding visit(APatternBinding p, A arg)
    {
      Pattern pattern_ = p.pattern_.accept(this, arg);
      Expr expr_ = p.expr_.accept(this, arg);
      return new APatternBinding(pattern_, expr_);
    }

    /* VariantFieldType */
    public VariantFieldType visit(AVariantFieldType p, A arg)
    {
      String stellaident_ = p.stellaident_;
      OptionalTyping optionaltyping_ = p.optionaltyping_.accept(this, arg);
      return new AVariantFieldType(stellaident_, optionaltyping_);
    }

    /* RecordFieldType */
    public RecordFieldType visit(ARecordFieldType p, A arg)
    {
      String stellaident_ = p.stellaident_;
      Type type_ = p.type_.accept(this, arg);
      return new ARecordFieldType(stellaident_, type_);
    }

    /* Typing */
    public Typing visit(ATyping p, A arg)
    {
      Expr expr_ = p.expr_.accept(this, arg);
      Type type_ = p.type_.accept(this, arg);
      return new ATyping(expr_, type_);
    }
}
