// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella;

import org.syntax.stella.Absyn.ABinding;
import org.syntax.stella.Absyn.ALabelledPattern;
import org.syntax.stella.Absyn.ALocalDecl;
import org.syntax.stella.Absyn.AMatchCase;
import org.syntax.stella.Absyn.AParamDecl;
import org.syntax.stella.Absyn.APatternBinding;
import org.syntax.stella.Absyn.AProgram;
import org.syntax.stella.Absyn.ARecordFieldType;
import org.syntax.stella.Absyn.ATyping;
import org.syntax.stella.Absyn.AVariantFieldType;
import org.syntax.stella.Absyn.Abstraction;
import org.syntax.stella.Absyn.Add;
import org.syntax.stella.Absyn.AnExtension;
import org.syntax.stella.Absyn.Annotation;
import org.syntax.stella.Absyn.Application;
import org.syntax.stella.Absyn.Assign;
import org.syntax.stella.Absyn.Binding;
import org.syntax.stella.Absyn.ConsList;
import org.syntax.stella.Absyn.ConstFalse;
import org.syntax.stella.Absyn.ConstInt;
import org.syntax.stella.Absyn.ConstMemory;
import org.syntax.stella.Absyn.ConstTrue;
import org.syntax.stella.Absyn.ConstUnit;
import org.syntax.stella.Absyn.Decl;
import org.syntax.stella.Absyn.DeclExceptionType;
import org.syntax.stella.Absyn.DeclExceptionVariant;
import org.syntax.stella.Absyn.DeclFun;
import org.syntax.stella.Absyn.DeclFunGeneric;
import org.syntax.stella.Absyn.DeclTypeAlias;
import org.syntax.stella.Absyn.Deref;
import org.syntax.stella.Absyn.Divide;
import org.syntax.stella.Absyn.DotRecord;
import org.syntax.stella.Absyn.DotTuple;
import org.syntax.stella.Absyn.Equal;
import org.syntax.stella.Absyn.Expr;
import org.syntax.stella.Absyn.Extension;
import org.syntax.stella.Absyn.Fix;
import org.syntax.stella.Absyn.Fold;
import org.syntax.stella.Absyn.GreaterThan;
import org.syntax.stella.Absyn.GreaterThanOrEqual;
import org.syntax.stella.Absyn.Head;
import org.syntax.stella.Absyn.If;
import org.syntax.stella.Absyn.Inl;
import org.syntax.stella.Absyn.InlineAnnotation;
import org.syntax.stella.Absyn.Inr;
import org.syntax.stella.Absyn.IsEmpty;
import org.syntax.stella.Absyn.IsZero;
import org.syntax.stella.Absyn.LabelledPattern;
import org.syntax.stella.Absyn.LanguageCore;
import org.syntax.stella.Absyn.LessThan;
import org.syntax.stella.Absyn.LessThanOrEqual;
import org.syntax.stella.Absyn.Let;
import org.syntax.stella.Absyn.LetRec;
import org.syntax.stella.Absyn.List;
import org.syntax.stella.Absyn.LogicAnd;
import org.syntax.stella.Absyn.LogicNot;
import org.syntax.stella.Absyn.LogicOr;
import org.syntax.stella.Absyn.Match;
import org.syntax.stella.Absyn.MatchCase;
import org.syntax.stella.Absyn.Multiply;
import org.syntax.stella.Absyn.NatRec;
import org.syntax.stella.Absyn.NoExprData;
import org.syntax.stella.Absyn.NoPatternData;
import org.syntax.stella.Absyn.NoReturnType;
import org.syntax.stella.Absyn.NoThrowType;
import org.syntax.stella.Absyn.NoTyping;
import org.syntax.stella.Absyn.NotEqual;
import org.syntax.stella.Absyn.Panic;
import org.syntax.stella.Absyn.ParamDecl;
import org.syntax.stella.Absyn.Pattern;
import org.syntax.stella.Absyn.PatternAsc;
import org.syntax.stella.Absyn.PatternBinding;
import org.syntax.stella.Absyn.PatternCastAs;
import org.syntax.stella.Absyn.PatternCons;
import org.syntax.stella.Absyn.PatternFalse;
import org.syntax.stella.Absyn.PatternInl;
import org.syntax.stella.Absyn.PatternInr;
import org.syntax.stella.Absyn.PatternInt;
import org.syntax.stella.Absyn.PatternList;
import org.syntax.stella.Absyn.PatternRecord;
import org.syntax.stella.Absyn.PatternSucc;
import org.syntax.stella.Absyn.PatternTrue;
import org.syntax.stella.Absyn.PatternTuple;
import org.syntax.stella.Absyn.PatternUnit;
import org.syntax.stella.Absyn.PatternVar;
import org.syntax.stella.Absyn.PatternVariant;
import org.syntax.stella.Absyn.Pred;
import org.syntax.stella.Absyn.Record;
import org.syntax.stella.Absyn.RecordFieldType;
import org.syntax.stella.Absyn.Ref;
import org.syntax.stella.Absyn.Sequence;
import org.syntax.stella.Absyn.SomeExprData;
import org.syntax.stella.Absyn.SomePatternData;
import org.syntax.stella.Absyn.SomeReturnType;
import org.syntax.stella.Absyn.SomeThrowType;
import org.syntax.stella.Absyn.SomeTyping;
import org.syntax.stella.Absyn.Subtract;
import org.syntax.stella.Absyn.Succ;
import org.syntax.stella.Absyn.Tail;
import org.syntax.stella.Absyn.Throw;
import org.syntax.stella.Absyn.TryCastAs;
import org.syntax.stella.Absyn.TryCatch;
import org.syntax.stella.Absyn.TryWith;
import org.syntax.stella.Absyn.Tuple;
import org.syntax.stella.Absyn.Type;
import org.syntax.stella.Absyn.TypeAbstraction;
import org.syntax.stella.Absyn.TypeApplication;
import org.syntax.stella.Absyn.TypeAsc;
import org.syntax.stella.Absyn.TypeAuto;
import org.syntax.stella.Absyn.TypeBool;
import org.syntax.stella.Absyn.TypeBottom;
import org.syntax.stella.Absyn.TypeCast;
import org.syntax.stella.Absyn.TypeForAll;
import org.syntax.stella.Absyn.TypeFun;
import org.syntax.stella.Absyn.TypeList;
import org.syntax.stella.Absyn.TypeNat;
import org.syntax.stella.Absyn.TypeRec;
import org.syntax.stella.Absyn.TypeRecord;
import org.syntax.stella.Absyn.TypeRef;
import org.syntax.stella.Absyn.TypeSum;
import org.syntax.stella.Absyn.TypeTop;
import org.syntax.stella.Absyn.TypeTuple;
import org.syntax.stella.Absyn.TypeUnit;
import org.syntax.stella.Absyn.TypeVar;
import org.syntax.stella.Absyn.TypeVariant;
import org.syntax.stella.Absyn.Unfold;
import org.syntax.stella.Absyn.Var;
import org.syntax.stella.Absyn.Variant;
import org.syntax.stella.Absyn.VariantFieldType;

/** Fold Visitor */
public abstract class FoldVisitor<R,A> implements AllVisitor<R,A> {
    public abstract R leaf(A arg);
    public abstract R combine(R x, R y, A arg);

/* Program */
    public R visit(AProgram p, A arg) {
      R r = leaf(arg);
      r = combine(p.languagedecl_.accept(this, arg), r, arg);
      for (Extension x : p.listextension_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (Decl x : p.listdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* LanguageDecl */
    public R visit(LanguageCore p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Extension */
    public R visit(AnExtension p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* Decl */
    public R visit(DeclFun p, A arg) {
      R r = leaf(arg);
      for (Annotation x : p.listannotation_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (ParamDecl x : p.listparamdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.returntype_.accept(this, arg), r, arg);
      r = combine(p.throwtype_.accept(this, arg), r, arg);
      for (Decl x : p.listdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(DeclFunGeneric p, A arg) {
      R r = leaf(arg);
      for (Annotation x : p.listannotation_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      for (ParamDecl x : p.listparamdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.returntype_.accept(this, arg), r, arg);
      r = combine(p.throwtype_.accept(this, arg), r, arg);
      for (Decl x : p.listdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(DeclTypeAlias p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(DeclExceptionType p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(DeclExceptionVariant p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* LocalDecl */
    public R visit(ALocalDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.decl_.accept(this, arg), r, arg);
      return r;
    }

/* Annotation */
    public R visit(InlineAnnotation p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* ParamDecl */
    public R visit(AParamDecl p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* ReturnType */
    public R visit(NoReturnType p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(SomeReturnType p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* ThrowType */
    public R visit(NoThrowType p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(SomeThrowType p, A arg) {
      R r = leaf(arg);
      for (Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Type */
    public R visit(TypeAuto p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(TypeFun p, A arg) {
      R r = leaf(arg);
      for (Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeForAll p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeRec p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeSum p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_1.accept(this, arg), r, arg);
      r = combine(p.type_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeTuple p, A arg) {
      R r = leaf(arg);
      for (Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(TypeRecord p, A arg) {
      R r = leaf(arg);
      for (RecordFieldType x : p.listrecordfieldtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(TypeVariant p, A arg) {
      R r = leaf(arg);
      for (VariantFieldType x : p.listvariantfieldtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(TypeList p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeBool p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(TypeNat p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(TypeUnit p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(TypeTop p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(TypeBottom p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(TypeRef p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeVar p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* MatchCase */
    public R visit(AMatchCase p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* OptionalTyping */
    public R visit(NoTyping p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(SomeTyping p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* PatternData */
    public R visit(NoPatternData p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(SomePatternData p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }

/* ExprData */
    public R visit(NoExprData p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(SomeExprData p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Pattern */
    public R visit(PatternCastAs p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternAsc p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternVariant p, A arg) {
      R r = leaf(arg);
      r = combine(p.patterndata_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternInl p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternInr p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternTuple p, A arg) {
      R r = leaf(arg);
      for (Pattern x : p.listpattern_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(PatternRecord p, A arg) {
      R r = leaf(arg);
      for (LabelledPattern x : p.listlabelledpattern_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(PatternList p, A arg) {
      R r = leaf(arg);
      for (Pattern x : p.listpattern_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(PatternCons p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_1.accept(this, arg), r, arg);
      r = combine(p.pattern_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternFalse p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(PatternTrue p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(PatternUnit p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(PatternInt p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(PatternSucc p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(PatternVar p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* LabelledPattern */
    public R visit(ALabelledPattern p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      return r;
    }

/* Binding */
    public R visit(ABinding p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Expr */
    public R visit(Sequence p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Let p, A arg) {
      R r = leaf(arg);
      for (PatternBinding x : p.listpatternbinding_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(LetRec p, A arg) {
      R r = leaf(arg);
      for (PatternBinding x : p.listpatternbinding_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeAbstraction p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Assign p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(If p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      r = combine(p.expr_3.accept(this, arg), r, arg);
      return r;
    }
    public R visit(LessThan p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(LessThanOrEqual p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(GreaterThan p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(GreaterThanOrEqual p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Equal p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(NotEqual p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeAsc p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TypeCast p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Abstraction p, A arg) {
      R r = leaf(arg);
      for (ParamDecl x : p.listparamdecl_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Variant p, A arg) {
      R r = leaf(arg);
      r = combine(p.exprdata_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Match p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      for (MatchCase x : p.listmatchcase_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(List p, A arg) {
      R r = leaf(arg);
      for (Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(Add p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Subtract p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(LogicOr p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Multiply p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Divide p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(LogicAnd p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Ref p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Deref p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Application p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      for (Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(TypeApplication p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      for (Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(DotRecord p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(DotTuple p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Tuple p, A arg) {
      R r = leaf(arg);
      for (Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(Record p, A arg) {
      R r = leaf(arg);
      for (Binding x : p.listbinding_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(ConsList p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Head p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(IsEmpty p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Tail p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Panic p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(Throw p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TryCatch p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TryWith p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(TryCastAs p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      r = combine(p.expr_3.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Inl p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Inr p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Succ p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(LogicNot p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Pred p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(IsZero p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Fix p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(NatRec p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      r = combine(p.expr_3.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Fold p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(Unfold p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(ConstTrue p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(ConstFalse p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(ConstUnit p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(ConstInt p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(ConstMemory p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(Var p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* PatternBinding */
    public R visit(APatternBinding p, A arg) {
      R r = leaf(arg);
      r = combine(p.pattern_.accept(this, arg), r, arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* VariantFieldType */
    public R visit(AVariantFieldType p, A arg) {
      R r = leaf(arg);
      r = combine(p.optionaltyping_.accept(this, arg), r, arg);
      return r;
    }

/* RecordFieldType */
    public R visit(ARecordFieldType p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* Typing */
    public R visit(ATyping p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }


}
