// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella;

import org.syntax.stella.Absyn.ABinding;
import org.syntax.stella.Absyn.ALabelledPattern;
import org.syntax.stella.Absyn.ALocalDecl;
import org.syntax.stella.Absyn.AMatchCase;
import org.syntax.stella.Absyn.AParamDecl;
import org.syntax.stella.Absyn.APatternBinding;
import org.syntax.stella.Absyn.AProgram;
import org.syntax.stella.Absyn.ARecordFieldType;
import org.syntax.stella.Absyn.ATyping;
import org.syntax.stella.Absyn.AVariantFieldType;
import org.syntax.stella.Absyn.Abstraction;
import org.syntax.stella.Absyn.Add;
import org.syntax.stella.Absyn.AnExtension;
import org.syntax.stella.Absyn.Annotation;
import org.syntax.stella.Absyn.Application;
import org.syntax.stella.Absyn.Assign;
import org.syntax.stella.Absyn.Binding;
import org.syntax.stella.Absyn.ConsList;
import org.syntax.stella.Absyn.ConstFalse;
import org.syntax.stella.Absyn.ConstInt;
import org.syntax.stella.Absyn.ConstMemory;
import org.syntax.stella.Absyn.ConstTrue;
import org.syntax.stella.Absyn.ConstUnit;
import org.syntax.stella.Absyn.Decl;
import org.syntax.stella.Absyn.DeclExceptionType;
import org.syntax.stella.Absyn.DeclExceptionVariant;
import org.syntax.stella.Absyn.DeclFun;
import org.syntax.stella.Absyn.DeclFunGeneric;
import org.syntax.stella.Absyn.DeclTypeAlias;
import org.syntax.stella.Absyn.Deref;
import org.syntax.stella.Absyn.Divide;
import org.syntax.stella.Absyn.DotRecord;
import org.syntax.stella.Absyn.DotTuple;
import org.syntax.stella.Absyn.Equal;
import org.syntax.stella.Absyn.Expr;
import org.syntax.stella.Absyn.ExprData;
import org.syntax.stella.Absyn.Extension;
import org.syntax.stella.Absyn.Fix;
import org.syntax.stella.Absyn.Fold;
import org.syntax.stella.Absyn.GreaterThan;
import org.syntax.stella.Absyn.GreaterThanOrEqual;
import org.syntax.stella.Absyn.Head;
import org.syntax.stella.Absyn.If;
import org.syntax.stella.Absyn.Inl;
import org.syntax.stella.Absyn.InlineAnnotation;
import org.syntax.stella.Absyn.Inr;
import org.syntax.stella.Absyn.IsEmpty;
import org.syntax.stella.Absyn.IsZero;
import org.syntax.stella.Absyn.LabelledPattern;
import org.syntax.stella.Absyn.LanguageCore;
import org.syntax.stella.Absyn.LanguageDecl;
import org.syntax.stella.Absyn.LessThan;
import org.syntax.stella.Absyn.LessThanOrEqual;
import org.syntax.stella.Absyn.Let;
import org.syntax.stella.Absyn.LetRec;
import org.syntax.stella.Absyn.List;
import org.syntax.stella.Absyn.ListAnnotation;
import org.syntax.stella.Absyn.ListBinding;
import org.syntax.stella.Absyn.ListDecl;
import org.syntax.stella.Absyn.ListExpr;
import org.syntax.stella.Absyn.ListExtension;
import org.syntax.stella.Absyn.ListExtensionName;
import org.syntax.stella.Absyn.ListLabelledPattern;
import org.syntax.stella.Absyn.ListLocalDecl;
import org.syntax.stella.Absyn.ListMatchCase;
import org.syntax.stella.Absyn.ListParamDecl;
import org.syntax.stella.Absyn.ListPattern;
import org.syntax.stella.Absyn.ListPatternBinding;
import org.syntax.stella.Absyn.ListRecordFieldType;
import org.syntax.stella.Absyn.ListStellaIdent;
import org.syntax.stella.Absyn.ListType;
import org.syntax.stella.Absyn.ListVariantFieldType;
import org.syntax.stella.Absyn.LocalDecl;
import org.syntax.stella.Absyn.LogicAnd;
import org.syntax.stella.Absyn.LogicNot;
import org.syntax.stella.Absyn.LogicOr;
import org.syntax.stella.Absyn.Match;
import org.syntax.stella.Absyn.MatchCase;
import org.syntax.stella.Absyn.Multiply;
import org.syntax.stella.Absyn.NatRec;
import org.syntax.stella.Absyn.NoExprData;
import org.syntax.stella.Absyn.NoPatternData;
import org.syntax.stella.Absyn.NoReturnType;
import org.syntax.stella.Absyn.NoThrowType;
import org.syntax.stella.Absyn.NoTyping;
import org.syntax.stella.Absyn.NotEqual;
import org.syntax.stella.Absyn.OptionalTyping;
import org.syntax.stella.Absyn.Panic;
import org.syntax.stella.Absyn.ParamDecl;
import org.syntax.stella.Absyn.Pattern;
import org.syntax.stella.Absyn.PatternAsc;
import org.syntax.stella.Absyn.PatternBinding;
import org.syntax.stella.Absyn.PatternCastAs;
import org.syntax.stella.Absyn.PatternCons;
import org.syntax.stella.Absyn.PatternData;
import org.syntax.stella.Absyn.PatternFalse;
import org.syntax.stella.Absyn.PatternInl;
import org.syntax.stella.Absyn.PatternInr;
import org.syntax.stella.Absyn.PatternInt;
import org.syntax.stella.Absyn.PatternList;
import org.syntax.stella.Absyn.PatternRecord;
import org.syntax.stella.Absyn.PatternSucc;
import org.syntax.stella.Absyn.PatternTrue;
import org.syntax.stella.Absyn.PatternTuple;
import org.syntax.stella.Absyn.PatternUnit;
import org.syntax.stella.Absyn.PatternVar;
import org.syntax.stella.Absyn.PatternVariant;
import org.syntax.stella.Absyn.Pred;
import org.syntax.stella.Absyn.Program;
import org.syntax.stella.Absyn.Record;
import org.syntax.stella.Absyn.RecordFieldType;
import org.syntax.stella.Absyn.Ref;
import org.syntax.stella.Absyn.ReturnType;
import org.syntax.stella.Absyn.Sequence;
import org.syntax.stella.Absyn.SomeExprData;
import org.syntax.stella.Absyn.SomePatternData;
import org.syntax.stella.Absyn.SomeReturnType;
import org.syntax.stella.Absyn.SomeThrowType;
import org.syntax.stella.Absyn.SomeTyping;
import org.syntax.stella.Absyn.Subtract;
import org.syntax.stella.Absyn.Succ;
import org.syntax.stella.Absyn.Tail;
import org.syntax.stella.Absyn.Throw;
import org.syntax.stella.Absyn.ThrowType;
import org.syntax.stella.Absyn.TryCastAs;
import org.syntax.stella.Absyn.TryCatch;
import org.syntax.stella.Absyn.TryWith;
import org.syntax.stella.Absyn.Tuple;
import org.syntax.stella.Absyn.Type;
import org.syntax.stella.Absyn.TypeAbstraction;
import org.syntax.stella.Absyn.TypeApplication;
import org.syntax.stella.Absyn.TypeAsc;
import org.syntax.stella.Absyn.TypeAuto;
import org.syntax.stella.Absyn.TypeBool;
import org.syntax.stella.Absyn.TypeBottom;
import org.syntax.stella.Absyn.TypeCast;
import org.syntax.stella.Absyn.TypeForAll;
import org.syntax.stella.Absyn.TypeFun;
import org.syntax.stella.Absyn.TypeList;
import org.syntax.stella.Absyn.TypeNat;
import org.syntax.stella.Absyn.TypeRec;
import org.syntax.stella.Absyn.TypeRecord;
import org.syntax.stella.Absyn.TypeRef;
import org.syntax.stella.Absyn.TypeSum;
import org.syntax.stella.Absyn.TypeTop;
import org.syntax.stella.Absyn.TypeTuple;
import org.syntax.stella.Absyn.TypeUnit;
import org.syntax.stella.Absyn.TypeVar;
import org.syntax.stella.Absyn.TypeVariant;
import org.syntax.stella.Absyn.Typing;
import org.syntax.stella.Absyn.Unfold;
import org.syntax.stella.Absyn.Var;
import org.syntax.stella.Absyn.Variant;
import org.syntax.stella.Absyn.VariantFieldType;

import java.util.Iterator;
import java.util.Locale;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(Program foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Program foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListStellaIdent foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListStellaIdent foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(LanguageDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(LanguageDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Extension foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Extension foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListExtensionName foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListExtensionName foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListExtension foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListExtension foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Decl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Decl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(LocalDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(LocalDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListLocalDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListLocalDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Annotation foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Annotation foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListAnnotation foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListAnnotation foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ParamDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ParamDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListParamDecl foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListParamDecl foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ReturnType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ReturnType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ThrowType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ThrowType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Type foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Type foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(MatchCase foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(MatchCase foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListMatchCase foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListMatchCase foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(OptionalTyping foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(OptionalTyping foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(PatternData foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(PatternData foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ExprData foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ExprData foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Pattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Pattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListPattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListPattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(LabelledPattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(LabelledPattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListLabelledPattern foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListLabelledPattern foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Binding foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Binding foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListBinding foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListBinding foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Expr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Expr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListExpr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListExpr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(PatternBinding foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(PatternBinding foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListPatternBinding foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListPatternBinding foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(VariantFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(VariantFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListVariantFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListVariantFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(RecordFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(RecordFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(ListRecordFieldType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(ListRecordFieldType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(Typing foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(Typing foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(Program foo, int _i_)
  {
    if (foo instanceof AProgram)
    {
       AProgram _aprogram = (AProgram) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_aprogram.languagedecl_, 0);
       pp(_aprogram.listextension_, 0);
       pp(_aprogram.listdecl_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListStellaIdent foo, int _i_)
  {
    ppListStellaIdent(foo.iterator(), _i_);
  }

  private static void ppListStellaIdent(Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListStellaIdent(it, _i_);
      }
    }
  }


  private static void pp(LanguageDecl foo, int _i_)
  {
    if (foo instanceof LanguageCore)
    {
       LanguageCore _languagecore = (LanguageCore) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("language");
       render("core");
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(Extension foo, int _i_)
  {
    if (foo instanceof AnExtension)
    {
       AnExtension _anextension = (AnExtension) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("extend");
       render("with");
       pp(_anextension.listextensionname_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListExtensionName foo, int _i_)
  {
    ppListExtensionName(foo.iterator(), _i_);
  }

  private static void ppListExtensionName(Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExtensionName(it, _i_);
      }
    }
  }


  private static void pp(ListExtension foo, int _i_)
  {
    ppListExtension(foo.iterator(), _i_);
  }

  private static void ppListExtension(Iterator<Extension> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      Extension el = it.next();
      pp(el, _i_); render(";"); ppListExtension(it, _i_);
    }
  }


  private static void pp(Decl foo, int _i_)
  {
    if (foo instanceof DeclFun)
    {
       DeclFun _declfun = (DeclFun) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_declfun.listannotation_, 0);
       render("fn");
       pp(_declfun.stellaident_, 0);
       render("(");
       pp(_declfun.listparamdecl_, 0);
       render(")");
       pp(_declfun.returntype_, 0);
       pp(_declfun.throwtype_, 0);
       render("{");
       pp(_declfun.listdecl_, 0);
       render("return");
       pp(_declfun.expr_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof DeclFunGeneric)
    {
       DeclFunGeneric _declfungeneric = (DeclFunGeneric) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_declfungeneric.listannotation_, 0);
       render("generic");
       render("fn");
       pp(_declfungeneric.stellaident_, 0);
       render("[");
       pp(_declfungeneric.liststellaident_, 0);
       render("]");
       render("(");
       pp(_declfungeneric.listparamdecl_, 0);
       render(")");
       pp(_declfungeneric.returntype_, 0);
       pp(_declfungeneric.throwtype_, 0);
       render("{");
       pp(_declfungeneric.listdecl_, 0);
       render("return");
       pp(_declfungeneric.expr_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof DeclTypeAlias)
    {
       DeclTypeAlias _decltypealias = (DeclTypeAlias) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("type");
       pp(_decltypealias.stellaident_, 0);
       render("=");
       pp(_decltypealias.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof DeclExceptionType)
    {
       DeclExceptionType _declexceptiontype = (DeclExceptionType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("exception");
       render("type");
       render("=");
       pp(_declexceptiontype.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof DeclExceptionVariant)
    {
       DeclExceptionVariant _declexceptionvariant = (DeclExceptionVariant) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("exception");
       render("variant");
       pp(_declexceptionvariant.stellaident_, 0);
       render(":");
       pp(_declexceptionvariant.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListDecl foo, int _i_)
  {
    ppListDecl(foo.iterator(), _i_);
  }

  private static void ppListDecl(Iterator<Decl> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      Decl el = it.next();
      pp(el, _i_); ppListDecl(it, _i_);
    }
  }


  private static void pp(LocalDecl foo, int _i_)
  {
    if (foo instanceof ALocalDecl)
    {
       ALocalDecl _alocaldecl = (ALocalDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_alocaldecl.decl_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListLocalDecl foo, int _i_)
  {
    ppListLocalDecl(foo.iterator(), _i_);
  }

  private static void ppListLocalDecl(Iterator<LocalDecl> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      LocalDecl el = it.next();
      pp(el, _i_); render(";"); ppListLocalDecl(it, _i_);
    }
  }


  private static void pp(Annotation foo, int _i_)
  {
    if (foo instanceof InlineAnnotation)
    {
       InlineAnnotation _inlineannotation = (InlineAnnotation) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("inline");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListAnnotation foo, int _i_)
  {
    ppListAnnotation(foo.iterator(), _i_);
  }

  private static void ppListAnnotation(Iterator<Annotation> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      Annotation el = it.next();
      pp(el, _i_); ppListAnnotation(it, _i_);
    }
  }


  private static void pp(ParamDecl foo, int _i_)
  {
    if (foo instanceof AParamDecl)
    {
       AParamDecl _aparamdecl = (AParamDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_aparamdecl.stellaident_, 0);
       render(":");
       pp(_aparamdecl.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListParamDecl foo, int _i_)
  {
    ppListParamDecl(foo.iterator(), _i_);
  }

  private static void ppListParamDecl(Iterator<ParamDecl> it, int _i_)
  {
    if (it.hasNext())
    {
      ParamDecl el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListParamDecl(it, _i_);
      }
    }
  }


  private static void pp(ReturnType foo, int _i_)
  {
    if (foo instanceof NoReturnType)
    {
       NoReturnType _noreturntype = (NoReturnType) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof SomeReturnType)
    {
       SomeReturnType _somereturntype = (SomeReturnType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("->");
       pp(_somereturntype.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ThrowType foo, int _i_)
  {
    if (foo instanceof NoThrowType)
    {
       NoThrowType _nothrowtype = (NoThrowType) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof SomeThrowType)
    {
       SomeThrowType _somethrowtype = (SomeThrowType) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("throws");
       pp(_somethrowtype.listtype_, 9);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(Type foo, int _i_)
  {
    if (foo instanceof TypeAuto)
    {
       TypeAuto _typeauto = (TypeAuto) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("auto");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof TypeFun)
    {
       TypeFun _typefun = (TypeFun) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("fn");
       render("(");
       pp(_typefun.listtype_, 0);
       render(")");
       render("->");
       pp(_typefun.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof TypeForAll)
    {
       TypeForAll _typeforall = (TypeForAll) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("forall");
       pp(_typeforall.liststellaident_, 0);
       render(".");
       pp(_typeforall.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof TypeRec)
    {
       TypeRec _typerec = (TypeRec) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("µ");
       pp(_typerec.stellaident_, 0);
       render(".");
       pp(_typerec.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof TypeSum)
    {
       TypeSum _typesum = (TypeSum) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_typesum.type_1, 2);
       render("+");
       pp(_typesum.type_2, 2);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof TypeTuple)
    {
       TypeTuple _typetuple = (TypeTuple) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("{");
       pp(_typetuple.listtype_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof TypeRecord)
    {
       TypeRecord _typerecord = (TypeRecord) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("{");
       pp(_typerecord.listrecordfieldtype_, 0);
       render("}");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof TypeVariant)
    {
       TypeVariant _typevariant = (TypeVariant) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("<|");
       pp(_typevariant.listvariantfieldtype_, 0);
       render("|>");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof TypeList)
    {
       TypeList _typelist = (TypeList) foo;
       if (_i_ > 2) render(_L_PAREN);
       render("[");
       pp(_typelist.type_, 0);
       render("]");
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof TypeBool)
    {
       TypeBool _typebool = (TypeBool) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Bool");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeNat)
    {
       TypeNat _typenat = (TypeNat) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Nat");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeUnit)
    {
       TypeUnit _typeunit = (TypeUnit) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Unit");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeTop)
    {
       TypeTop _typetop = (TypeTop) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Top");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeBottom)
    {
       TypeBottom _typebottom = (TypeBottom) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("Bot");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeRef)
    {
       TypeRef _typeref = (TypeRef) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("&");
       pp(_typeref.type_, 2);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeVar)
    {
       TypeVar _typevar = (TypeVar) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_typevar.stellaident_, 0);
       if (_i_ > 3) render(_R_PAREN);
    }

  }

  private static void pp(ListType foo, int _i_)
  {
    ppListType(foo.iterator(), _i_);
  }

  private static void ppListType(Iterator<Type> it, int _i_)
  {
    if (it.hasNext())
    {
      Type el = it.next();
      if (!it.hasNext())
      { /* last */
        switch(_i_)
    {
      case 9: pp(el, _i_); break;
      case 0: pp(el, _i_); break;
    }
      }
      else
      { /* cons */
        switch(_i_)
    {
      case 9: pp(el, _i_); render(","); ppListType(it, _i_); break;
      case 0: pp(el, _i_); render(","); ppListType(it, _i_); break;
    }
      }
    }
  }


  private static void pp(MatchCase foo, int _i_)
  {
    if (foo instanceof AMatchCase)
    {
       AMatchCase _amatchcase = (AMatchCase) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_amatchcase.pattern_, 0);
       render("=>");
       pp(_amatchcase.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListMatchCase foo, int _i_)
  {
    ppListMatchCase(foo.iterator(), _i_);
  }

  private static void ppListMatchCase(Iterator<MatchCase> it, int _i_)
  {
    if (it.hasNext())
    {
      MatchCase el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render("|"); ppListMatchCase(it, _i_);
      }
    }
  }


  private static void pp(OptionalTyping foo, int _i_)
  {
    if (foo instanceof NoTyping)
    {
       NoTyping _notyping = (NoTyping) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof SomeTyping)
    {
       SomeTyping _sometyping = (SomeTyping) foo;
       if (_i_ > 0) render(_L_PAREN);
       render(":");
       pp(_sometyping.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(PatternData foo, int _i_)
  {
    if (foo instanceof NoPatternData)
    {
       NoPatternData _nopatterndata = (NoPatternData) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof SomePatternData)
    {
       SomePatternData _somepatterndata = (SomePatternData) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("=");
       pp(_somepatterndata.pattern_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ExprData foo, int _i_)
  {
    if (foo instanceof NoExprData)
    {
       NoExprData _noexprdata = (NoExprData) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof SomeExprData)
    {
       SomeExprData _someexprdata = (SomeExprData) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("=");
       pp(_someexprdata.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(Pattern foo, int _i_)
  {
    if (foo instanceof PatternCastAs)
    {
       PatternCastAs _patterncastas = (PatternCastAs) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_patterncastas.pattern_, 0);
       render("cast");
       render("as");
       pp(_patterncastas.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternAsc)
    {
       PatternAsc _patternasc = (PatternAsc) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_patternasc.pattern_, 0);
       render("as");
       pp(_patternasc.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternVariant)
    {
       PatternVariant _patternvariant = (PatternVariant) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("<|");
       pp(_patternvariant.stellaident_, 0);
       pp(_patternvariant.patterndata_, 0);
       render("|>");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternInl)
    {
       PatternInl _patterninl = (PatternInl) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("inl");
       render("(");
       pp(_patterninl.pattern_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternInr)
    {
       PatternInr _patterninr = (PatternInr) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("inr");
       render("(");
       pp(_patterninr.pattern_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternTuple)
    {
       PatternTuple _patterntuple = (PatternTuple) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("{");
       pp(_patterntuple.listpattern_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternRecord)
    {
       PatternRecord _patternrecord = (PatternRecord) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("{");
       pp(_patternrecord.listlabelledpattern_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternList)
    {
       PatternList _patternlist = (PatternList) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("[");
       pp(_patternlist.listpattern_, 0);
       render("]");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternCons)
    {
       PatternCons _patterncons = (PatternCons) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("cons");
       render("(");
       pp(_patterncons.pattern_1, 0);
       render(",");
       pp(_patterncons.pattern_2, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternFalse)
    {
       PatternFalse _patternfalse = (PatternFalse) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("false");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternTrue)
    {
       PatternTrue _patterntrue = (PatternTrue) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("true");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternUnit)
    {
       PatternUnit _patternunit = (PatternUnit) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("unit");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternInt)
    {
       PatternInt _patternint = (PatternInt) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_patternint.integer_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternSucc)
    {
       PatternSucc _patternsucc = (PatternSucc) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("succ");
       render("(");
       pp(_patternsucc.pattern_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof PatternVar)
    {
       PatternVar _patternvar = (PatternVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_patternvar.stellaident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListPattern foo, int _i_)
  {
    ppListPattern(foo.iterator(), _i_);
  }

  private static void ppListPattern(Iterator<Pattern> it, int _i_)
  {
    if (it.hasNext())
    {
      Pattern el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListPattern(it, _i_);
      }
    }
  }


  private static void pp(LabelledPattern foo, int _i_)
  {
    if (foo instanceof ALabelledPattern)
    {
       ALabelledPattern _alabelledpattern = (ALabelledPattern) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_alabelledpattern.stellaident_, 0);
       render("=");
       pp(_alabelledpattern.pattern_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListLabelledPattern foo, int _i_)
  {
    ppListLabelledPattern(foo.iterator(), _i_);
  }

  private static void ppListLabelledPattern(Iterator<LabelledPattern> it, int _i_)
  {
    if (it.hasNext())
    {
      LabelledPattern el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListLabelledPattern(it, _i_);
      }
    }
  }


  private static void pp(Binding foo, int _i_)
  {
    if (foo instanceof ABinding)
    {
       ABinding _abinding = (ABinding) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_abinding.stellaident_, 0);
       render("=");
       pp(_abinding.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListBinding foo, int _i_)
  {
    ppListBinding(foo.iterator(), _i_);
  }

  private static void ppListBinding(Iterator<Binding> it, int _i_)
  {
    if (it.hasNext())
    {
      Binding el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListBinding(it, _i_);
      }
    }
  }


  private static void pp(Expr foo, int _i_)
  {
    if (foo instanceof Sequence)
    {
       Sequence _sequence = (Sequence) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_sequence.expr_1, 1);
       render(";");
       pp(_sequence.expr_2, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof Let)
    {
       Let _let = (Let) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("let");
       pp(_let.listpatternbinding_, 0);
       render("in");
       pp(_let.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof LetRec)
    {
       LetRec _letrec = (LetRec) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("letrec");
       pp(_letrec.listpatternbinding_, 0);
       render("in");
       pp(_letrec.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof TypeAbstraction)
    {
       TypeAbstraction _typeabstraction = (TypeAbstraction) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("generic");
       render("[");
       pp(_typeabstraction.liststellaident_, 0);
       render("]");
       pp(_typeabstraction.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof Assign)
    {
       Assign _assign = (Assign) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_assign.expr_1, 2);
       render(":=");
       pp(_assign.expr_2, 1);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof If)
    {
       If _if = (If) foo;
       if (_i_ > 1) render(_L_PAREN);
       render("if");
       pp(_if.expr_1, 1);
       render("then");
       pp(_if.expr_2, 1);
       render("else");
       pp(_if.expr_3, 1);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof LessThan)
    {
       LessThan _lessthan = (LessThan) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_lessthan.expr_1, 3);
       render("<");
       pp(_lessthan.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof LessThanOrEqual)
    {
       LessThanOrEqual _lessthanorequal = (LessThanOrEqual) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_lessthanorequal.expr_1, 3);
       render("<=");
       pp(_lessthanorequal.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof GreaterThan)
    {
       GreaterThan _greaterthan = (GreaterThan) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_greaterthan.expr_1, 3);
       render(">");
       pp(_greaterthan.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof GreaterThanOrEqual)
    {
       GreaterThanOrEqual _greaterthanorequal = (GreaterThanOrEqual) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_greaterthanorequal.expr_1, 3);
       render(">=");
       pp(_greaterthanorequal.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof Equal)
    {
       Equal _equal = (Equal) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_equal.expr_1, 3);
       render("==");
       pp(_equal.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof NotEqual)
    {
       NotEqual _notequal = (NotEqual) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_notequal.expr_1, 3);
       render("!=");
       pp(_notequal.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof TypeAsc)
    {
       TypeAsc _typeasc = (TypeAsc) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_typeasc.expr_, 3);
       render("as");
       pp(_typeasc.type_, 2);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof TypeCast)
    {
       TypeCast _typecast = (TypeCast) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_typecast.expr_, 3);
       render("cast");
       render("as");
       pp(_typecast.type_, 2);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof Abstraction)
    {
       Abstraction _abstraction = (Abstraction) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("fn");
       render("(");
       pp(_abstraction.listparamdecl_, 0);
       render(")");
       render("{");
       render("return");
       pp(_abstraction.expr_, 0);
       render("}");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof Variant)
    {
       Variant _variant = (Variant) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("<|");
       pp(_variant.stellaident_, 0);
       pp(_variant.exprdata_, 0);
       render("|>");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof Match)
    {
       Match _match = (Match) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("match");
       pp(_match.expr_, 2);
       render("{");
       pp(_match.listmatchcase_, 0);
       render("}");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof List)
    {
       List _list = (List) foo;
       if (_i_ > 3) render(_L_PAREN);
       render("[");
       pp(_list.listexpr_, 0);
       render("]");
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof Add)
    {
       Add _add = (Add) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_add.expr_1, 3);
       render("+");
       pp(_add.expr_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof Subtract)
    {
       Subtract _subtract = (Subtract) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_subtract.expr_1, 3);
       render("-");
       pp(_subtract.expr_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof LogicOr)
    {
       LogicOr _logicor = (LogicOr) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_logicor.expr_1, 3);
       render("or");
       pp(_logicor.expr_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof Multiply)
    {
       Multiply _multiply = (Multiply) foo;
       if (_i_ > 4) render(_L_PAREN);
       pp(_multiply.expr_1, 4);
       render("*");
       pp(_multiply.expr_2, 5);
       if (_i_ > 4) render(_R_PAREN);
    }
    else     if (foo instanceof Divide)
    {
       Divide _divide = (Divide) foo;
       if (_i_ > 4) render(_L_PAREN);
       pp(_divide.expr_1, 4);
       render("/");
       pp(_divide.expr_2, 5);
       if (_i_ > 4) render(_R_PAREN);
    }
    else     if (foo instanceof LogicAnd)
    {
       LogicAnd _logicand = (LogicAnd) foo;
       if (_i_ > 4) render(_L_PAREN);
       pp(_logicand.expr_1, 4);
       render("and");
       pp(_logicand.expr_2, 5);
       if (_i_ > 4) render(_R_PAREN);
    }
    else     if (foo instanceof Ref)
    {
       Ref _ref = (Ref) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("new");
       render("(");
       pp(_ref.expr_, 0);
       render(")");
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof Deref)
    {
       Deref _deref = (Deref) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("*");
       pp(_deref.expr_, 5);
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof Application)
    {
       Application _application = (Application) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_application.expr_, 6);
       render("(");
       pp(_application.listexpr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof TypeApplication)
    {
       TypeApplication _typeapplication = (TypeApplication) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_typeapplication.expr_, 6);
       render("[");
       pp(_typeapplication.listtype_, 0);
       render("]");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof DotRecord)
    {
       DotRecord _dotrecord = (DotRecord) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_dotrecord.expr_, 6);
       render(".");
       pp(_dotrecord.stellaident_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof DotTuple)
    {
       DotTuple _dottuple = (DotTuple) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_dottuple.expr_, 6);
       render(".");
       pp(_dottuple.integer_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Tuple)
    {
       Tuple _tuple = (Tuple) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("{");
       pp(_tuple.listexpr_, 0);
       render("}");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Record)
    {
       Record _record = (Record) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("{");
       pp(_record.listbinding_, 0);
       render("}");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof ConsList)
    {
       ConsList _conslist = (ConsList) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("cons");
       render("(");
       pp(_conslist.expr_1, 0);
       render(",");
       pp(_conslist.expr_2, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Head)
    {
       Head _head = (Head) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("List::head");
       render("(");
       pp(_head.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof IsEmpty)
    {
       IsEmpty _isempty = (IsEmpty) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("List::isempty");
       render("(");
       pp(_isempty.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Tail)
    {
       Tail _tail = (Tail) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("List::tail");
       render("(");
       pp(_tail.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Panic)
    {
       Panic _panic = (Panic) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("panic!");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Throw)
    {
       Throw _throw = (Throw) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("throw");
       render("(");
       pp(_throw.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof TryCatch)
    {
       TryCatch _trycatch = (TryCatch) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("try");
       render("{");
       pp(_trycatch.expr_1, 0);
       render("}");
       render("catch");
       render("{");
       pp(_trycatch.pattern_, 0);
       render("=>");
       pp(_trycatch.expr_2, 0);
       render("}");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof TryWith)
    {
       TryWith _trywith = (TryWith) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("try");
       render("{");
       pp(_trywith.expr_1, 0);
       render("}");
       render("with");
       render("{");
       pp(_trywith.expr_2, 0);
       render("}");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof TryCastAs)
    {
       TryCastAs _trycastas = (TryCastAs) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("try");
       render("{");
       pp(_trycastas.expr_1, 0);
       render("}");
       render("cast");
       render("as");
       pp(_trycastas.type_, 0);
       render("{");
       pp(_trycastas.pattern_, 0);
       render("=>");
       pp(_trycastas.expr_2, 0);
       render("}");
       render("with");
       render("{");
       pp(_trycastas.expr_3, 0);
       render("}");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Inl)
    {
       Inl _inl = (Inl) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("inl");
       render("(");
       pp(_inl.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Inr)
    {
       Inr _inr = (Inr) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("inr");
       render("(");
       pp(_inr.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Succ)
    {
       Succ _succ = (Succ) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("succ");
       render("(");
       pp(_succ.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof LogicNot)
    {
       LogicNot _logicnot = (LogicNot) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("not");
       render("(");
       pp(_logicnot.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Pred)
    {
       Pred _pred = (Pred) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("Nat::pred");
       render("(");
       pp(_pred.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof IsZero)
    {
       IsZero _iszero = (IsZero) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("Nat::iszero");
       render("(");
       pp(_iszero.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Fix)
    {
       Fix _fix = (Fix) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("fix");
       render("(");
       pp(_fix.expr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof NatRec)
    {
       NatRec _natrec = (NatRec) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("Nat::rec");
       render("(");
       pp(_natrec.expr_1, 0);
       render(",");
       pp(_natrec.expr_2, 0);
       render(",");
       pp(_natrec.expr_3, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Fold)
    {
       Fold _fold = (Fold) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("fold");
       render("[");
       pp(_fold.type_, 0);
       render("]");
       pp(_fold.expr_, 7);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof Unfold)
    {
       Unfold _unfold = (Unfold) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("unfold");
       render("[");
       pp(_unfold.type_, 0);
       render("]");
       pp(_unfold.expr_, 7);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof ConstTrue)
    {
       ConstTrue _consttrue = (ConstTrue) foo;
       if (_i_ > 7) render(_L_PAREN);
       render("true");
       if (_i_ > 7) render(_R_PAREN);
    }
    else     if (foo instanceof ConstFalse)
    {
       ConstFalse _constfalse = (ConstFalse) foo;
       if (_i_ > 7) render(_L_PAREN);
       render("false");
       if (_i_ > 7) render(_R_PAREN);
    }
    else     if (foo instanceof ConstUnit)
    {
       ConstUnit _constunit = (ConstUnit) foo;
       if (_i_ > 7) render(_L_PAREN);
       render("unit");
       if (_i_ > 7) render(_R_PAREN);
    }
    else     if (foo instanceof ConstInt)
    {
       ConstInt _constint = (ConstInt) foo;
       if (_i_ > 7) render(_L_PAREN);
       pp(_constint.integer_, 0);
       if (_i_ > 7) render(_R_PAREN);
    }
    else     if (foo instanceof ConstMemory)
    {
       ConstMemory _constmemory = (ConstMemory) foo;
       if (_i_ > 7) render(_L_PAREN);
       pp(_constmemory.memoryaddress_, 0);
       if (_i_ > 7) render(_R_PAREN);
    }
    else     if (foo instanceof Var)
    {
       Var _var = (Var) foo;
       if (_i_ > 7) render(_L_PAREN);
       pp(_var.stellaident_, 0);
       if (_i_ > 7) render(_R_PAREN);
    }

  }

  private static void pp(ListExpr foo, int _i_)
  {
    ppListExpr(foo.iterator(), _i_);
  }

  private static void ppListExpr(Iterator<Expr> it, int _i_)
  {
    if (it.hasNext())
    {
      Expr el = it.next();
      if (!it.hasNext())
      { /* last */
        switch(_i_)
    {
      case 2: pp(el, _i_); render(";"); break;
      case 0: pp(el, _i_); break;
    }
      }
      else
      { /* cons */
        switch(_i_)
    {
      case 2: pp(el, _i_); render(";"); ppListExpr(it, _i_); break;
      case 0: pp(el, _i_); render(","); ppListExpr(it, _i_); break;
    }
      }
    }
  }


  private static void pp(PatternBinding foo, int _i_)
  {
    if (foo instanceof APatternBinding)
    {
       APatternBinding _apatternbinding = (APatternBinding) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_apatternbinding.pattern_, 0);
       render("=");
       pp(_apatternbinding.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListPatternBinding foo, int _i_)
  {
    ppListPatternBinding(foo.iterator(), _i_);
  }

  private static void ppListPatternBinding(Iterator<PatternBinding> it, int _i_)
  {
    if (it.hasNext())
    {
      PatternBinding el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListPatternBinding(it, _i_);
      }
    }
  }


  private static void pp(VariantFieldType foo, int _i_)
  {
    if (foo instanceof AVariantFieldType)
    {
       AVariantFieldType _avariantfieldtype = (AVariantFieldType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_avariantfieldtype.stellaident_, 0);
       pp(_avariantfieldtype.optionaltyping_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListVariantFieldType foo, int _i_)
  {
    ppListVariantFieldType(foo.iterator(), _i_);
  }

  private static void ppListVariantFieldType(Iterator<VariantFieldType> it, int _i_)
  {
    if (it.hasNext())
    {
      VariantFieldType el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListVariantFieldType(it, _i_);
      }
    }
  }


  private static void pp(RecordFieldType foo, int _i_)
  {
    if (foo instanceof ARecordFieldType)
    {
       ARecordFieldType _arecordfieldtype = (ARecordFieldType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_arecordfieldtype.stellaident_, 0);
       render(":");
       pp(_arecordfieldtype.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(ListRecordFieldType foo, int _i_)
  {
    ppListRecordFieldType(foo.iterator(), _i_);
  }

  private static void ppListRecordFieldType(Iterator<RecordFieldType> it, int _i_)
  {
    if (it.hasNext())
    {
      RecordFieldType el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListRecordFieldType(it, _i_);
      }
    }
  }


  private static void pp(Typing foo, int _i_)
  {
    if (foo instanceof ATyping)
    {
       ATyping _atyping = (ATyping) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_atyping.expr_, 0);
       render(":");
       pp(_atyping.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(Program foo)
  {
    if (foo instanceof AProgram)
    {
       AProgram _aprogram = (AProgram) foo;
       render("(");
       render("AProgram");
       sh(_aprogram.languagedecl_);
       render("[");
       sh(_aprogram.listextension_);
       render("]");
       render("[");
       sh(_aprogram.listdecl_);
       render("]");
       render(")");
    }
  }

  private static void sh(ListStellaIdent foo)
  {
     for (Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(LanguageDecl foo)
  {
    if (foo instanceof LanguageCore)
    {
       LanguageCore _languagecore = (LanguageCore) foo;
       render("LanguageCore");
    }
  }

  private static void sh(Extension foo)
  {
    if (foo instanceof AnExtension)
    {
       AnExtension _anextension = (AnExtension) foo;
       render("(");
       render("AnExtension");
       render("[");
       sh(_anextension.listextensionname_);
       render("]");
       render(")");
    }
  }

  private static void sh(ListExtensionName foo)
  {
     for (Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(ListExtension foo)
  {
     for (Iterator<Extension> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(Decl foo)
  {
    if (foo instanceof DeclFun)
    {
       DeclFun _declfun = (DeclFun) foo;
       render("(");
       render("DeclFun");
       render("[");
       sh(_declfun.listannotation_);
       render("]");
       sh(_declfun.stellaident_);
       render("[");
       sh(_declfun.listparamdecl_);
       render("]");
       sh(_declfun.returntype_);
       sh(_declfun.throwtype_);
       render("[");
       sh(_declfun.listdecl_);
       render("]");
       sh(_declfun.expr_);
       render(")");
    }
    if (foo instanceof DeclFunGeneric)
    {
       DeclFunGeneric _declfungeneric = (DeclFunGeneric) foo;
       render("(");
       render("DeclFunGeneric");
       render("[");
       sh(_declfungeneric.listannotation_);
       render("]");
       sh(_declfungeneric.stellaident_);
       render("[");
       sh(_declfungeneric.liststellaident_);
       render("]");
       render("[");
       sh(_declfungeneric.listparamdecl_);
       render("]");
       sh(_declfungeneric.returntype_);
       sh(_declfungeneric.throwtype_);
       render("[");
       sh(_declfungeneric.listdecl_);
       render("]");
       sh(_declfungeneric.expr_);
       render(")");
    }
    if (foo instanceof DeclTypeAlias)
    {
       DeclTypeAlias _decltypealias = (DeclTypeAlias) foo;
       render("(");
       render("DeclTypeAlias");
       sh(_decltypealias.stellaident_);
       sh(_decltypealias.type_);
       render(")");
    }
    if (foo instanceof DeclExceptionType)
    {
       DeclExceptionType _declexceptiontype = (DeclExceptionType) foo;
       render("(");
       render("DeclExceptionType");
       sh(_declexceptiontype.type_);
       render(")");
    }
    if (foo instanceof DeclExceptionVariant)
    {
       DeclExceptionVariant _declexceptionvariant = (DeclExceptionVariant) foo;
       render("(");
       render("DeclExceptionVariant");
       sh(_declexceptionvariant.stellaident_);
       sh(_declexceptionvariant.type_);
       render(")");
    }
  }

  private static void sh(ListDecl foo)
  {
     for (Iterator<Decl> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(LocalDecl foo)
  {
    if (foo instanceof ALocalDecl)
    {
       ALocalDecl _alocaldecl = (ALocalDecl) foo;
       render("(");
       render("ALocalDecl");
       sh(_alocaldecl.decl_);
       render(")");
    }
  }

  private static void sh(ListLocalDecl foo)
  {
     for (Iterator<LocalDecl> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(Annotation foo)
  {
    if (foo instanceof InlineAnnotation)
    {
       InlineAnnotation _inlineannotation = (InlineAnnotation) foo;
       render("InlineAnnotation");
    }
  }

  private static void sh(ListAnnotation foo)
  {
     for (Iterator<Annotation> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(ParamDecl foo)
  {
    if (foo instanceof AParamDecl)
    {
       AParamDecl _aparamdecl = (AParamDecl) foo;
       render("(");
       render("AParamDecl");
       sh(_aparamdecl.stellaident_);
       sh(_aparamdecl.type_);
       render(")");
    }
  }

  private static void sh(ListParamDecl foo)
  {
     for (Iterator<ParamDecl> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(ReturnType foo)
  {
    if (foo instanceof NoReturnType)
    {
       NoReturnType _noreturntype = (NoReturnType) foo;
       render("NoReturnType");
    }
    if (foo instanceof SomeReturnType)
    {
       SomeReturnType _somereturntype = (SomeReturnType) foo;
       render("(");
       render("SomeReturnType");
       sh(_somereturntype.type_);
       render(")");
    }
  }

  private static void sh(ThrowType foo)
  {
    if (foo instanceof NoThrowType)
    {
       NoThrowType _nothrowtype = (NoThrowType) foo;
       render("NoThrowType");
    }
    if (foo instanceof SomeThrowType)
    {
       SomeThrowType _somethrowtype = (SomeThrowType) foo;
       render("(");
       render("SomeThrowType");
       render("[");
       sh(_somethrowtype.listtype_);
       render("]");
       render(")");
    }
  }

  private static void sh(Type foo)
  {
    if (foo instanceof TypeAuto)
    {
       TypeAuto _typeauto = (TypeAuto) foo;
       render("TypeAuto");
    }
    if (foo instanceof TypeFun)
    {
       TypeFun _typefun = (TypeFun) foo;
       render("(");
       render("TypeFun");
       render("[");
       sh(_typefun.listtype_);
       render("]");
       sh(_typefun.type_);
       render(")");
    }
    if (foo instanceof TypeForAll)
    {
       TypeForAll _typeforall = (TypeForAll) foo;
       render("(");
       render("TypeForAll");
       render("[");
       sh(_typeforall.liststellaident_);
       render("]");
       sh(_typeforall.type_);
       render(")");
    }
    if (foo instanceof TypeRec)
    {
       TypeRec _typerec = (TypeRec) foo;
       render("(");
       render("TypeRec");
       sh(_typerec.stellaident_);
       sh(_typerec.type_);
       render(")");
    }
    if (foo instanceof TypeSum)
    {
       TypeSum _typesum = (TypeSum) foo;
       render("(");
       render("TypeSum");
       sh(_typesum.type_1);
       sh(_typesum.type_2);
       render(")");
    }
    if (foo instanceof TypeTuple)
    {
       TypeTuple _typetuple = (TypeTuple) foo;
       render("(");
       render("TypeTuple");
       render("[");
       sh(_typetuple.listtype_);
       render("]");
       render(")");
    }
    if (foo instanceof TypeRecord)
    {
       TypeRecord _typerecord = (TypeRecord) foo;
       render("(");
       render("TypeRecord");
       render("[");
       sh(_typerecord.listrecordfieldtype_);
       render("]");
       render(")");
    }
    if (foo instanceof TypeVariant)
    {
       TypeVariant _typevariant = (TypeVariant) foo;
       render("(");
       render("TypeVariant");
       render("[");
       sh(_typevariant.listvariantfieldtype_);
       render("]");
       render(")");
    }
    if (foo instanceof TypeList)
    {
       TypeList _typelist = (TypeList) foo;
       render("(");
       render("TypeList");
       sh(_typelist.type_);
       render(")");
    }
    if (foo instanceof TypeBool)
    {
       TypeBool _typebool = (TypeBool) foo;
       render("TypeBool");
    }
    if (foo instanceof TypeNat)
    {
       TypeNat _typenat = (TypeNat) foo;
       render("TypeNat");
    }
    if (foo instanceof TypeUnit)
    {
       TypeUnit _typeunit = (TypeUnit) foo;
       render("TypeUnit");
    }
    if (foo instanceof TypeTop)
    {
       TypeTop _typetop = (TypeTop) foo;
       render("TypeTop");
    }
    if (foo instanceof TypeBottom)
    {
       TypeBottom _typebottom = (TypeBottom) foo;
       render("TypeBottom");
    }
    if (foo instanceof TypeRef)
    {
       TypeRef _typeref = (TypeRef) foo;
       render("(");
       render("TypeRef");
       sh(_typeref.type_);
       render(")");
    }
    if (foo instanceof TypeVar)
    {
       TypeVar _typevar = (TypeVar) foo;
       render("(");
       render("TypeVar");
       sh(_typevar.stellaident_);
       render(")");
    }
  }

  private static void sh(ListType foo)
  {
     for (Iterator<Type> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(MatchCase foo)
  {
    if (foo instanceof AMatchCase)
    {
       AMatchCase _amatchcase = (AMatchCase) foo;
       render("(");
       render("AMatchCase");
       sh(_amatchcase.pattern_);
       sh(_amatchcase.expr_);
       render(")");
    }
  }

  private static void sh(ListMatchCase foo)
  {
     for (Iterator<MatchCase> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(OptionalTyping foo)
  {
    if (foo instanceof NoTyping)
    {
       NoTyping _notyping = (NoTyping) foo;
       render("NoTyping");
    }
    if (foo instanceof SomeTyping)
    {
       SomeTyping _sometyping = (SomeTyping) foo;
       render("(");
       render("SomeTyping");
       sh(_sometyping.type_);
       render(")");
    }
  }

  private static void sh(PatternData foo)
  {
    if (foo instanceof NoPatternData)
    {
       NoPatternData _nopatterndata = (NoPatternData) foo;
       render("NoPatternData");
    }
    if (foo instanceof SomePatternData)
    {
       SomePatternData _somepatterndata = (SomePatternData) foo;
       render("(");
       render("SomePatternData");
       sh(_somepatterndata.pattern_);
       render(")");
    }
  }

  private static void sh(ExprData foo)
  {
    if (foo instanceof NoExprData)
    {
       NoExprData _noexprdata = (NoExprData) foo;
       render("NoExprData");
    }
    if (foo instanceof SomeExprData)
    {
       SomeExprData _someexprdata = (SomeExprData) foo;
       render("(");
       render("SomeExprData");
       sh(_someexprdata.expr_);
       render(")");
    }
  }

  private static void sh(Pattern foo)
  {
    if (foo instanceof PatternCastAs)
    {
       PatternCastAs _patterncastas = (PatternCastAs) foo;
       render("(");
       render("PatternCastAs");
       sh(_patterncastas.pattern_);
       sh(_patterncastas.type_);
       render(")");
    }
    if (foo instanceof PatternAsc)
    {
       PatternAsc _patternasc = (PatternAsc) foo;
       render("(");
       render("PatternAsc");
       sh(_patternasc.pattern_);
       sh(_patternasc.type_);
       render(")");
    }
    if (foo instanceof PatternVariant)
    {
       PatternVariant _patternvariant = (PatternVariant) foo;
       render("(");
       render("PatternVariant");
       sh(_patternvariant.stellaident_);
       sh(_patternvariant.patterndata_);
       render(")");
    }
    if (foo instanceof PatternInl)
    {
       PatternInl _patterninl = (PatternInl) foo;
       render("(");
       render("PatternInl");
       sh(_patterninl.pattern_);
       render(")");
    }
    if (foo instanceof PatternInr)
    {
       PatternInr _patterninr = (PatternInr) foo;
       render("(");
       render("PatternInr");
       sh(_patterninr.pattern_);
       render(")");
    }
    if (foo instanceof PatternTuple)
    {
       PatternTuple _patterntuple = (PatternTuple) foo;
       render("(");
       render("PatternTuple");
       render("[");
       sh(_patterntuple.listpattern_);
       render("]");
       render(")");
    }
    if (foo instanceof PatternRecord)
    {
       PatternRecord _patternrecord = (PatternRecord) foo;
       render("(");
       render("PatternRecord");
       render("[");
       sh(_patternrecord.listlabelledpattern_);
       render("]");
       render(")");
    }
    if (foo instanceof PatternList)
    {
       PatternList _patternlist = (PatternList) foo;
       render("(");
       render("PatternList");
       render("[");
       sh(_patternlist.listpattern_);
       render("]");
       render(")");
    }
    if (foo instanceof PatternCons)
    {
       PatternCons _patterncons = (PatternCons) foo;
       render("(");
       render("PatternCons");
       sh(_patterncons.pattern_1);
       sh(_patterncons.pattern_2);
       render(")");
    }
    if (foo instanceof PatternFalse)
    {
       PatternFalse _patternfalse = (PatternFalse) foo;
       render("PatternFalse");
    }
    if (foo instanceof PatternTrue)
    {
       PatternTrue _patterntrue = (PatternTrue) foo;
       render("PatternTrue");
    }
    if (foo instanceof PatternUnit)
    {
       PatternUnit _patternunit = (PatternUnit) foo;
       render("PatternUnit");
    }
    if (foo instanceof PatternInt)
    {
       PatternInt _patternint = (PatternInt) foo;
       render("(");
       render("PatternInt");
       sh(_patternint.integer_);
       render(")");
    }
    if (foo instanceof PatternSucc)
    {
       PatternSucc _patternsucc = (PatternSucc) foo;
       render("(");
       render("PatternSucc");
       sh(_patternsucc.pattern_);
       render(")");
    }
    if (foo instanceof PatternVar)
    {
       PatternVar _patternvar = (PatternVar) foo;
       render("(");
       render("PatternVar");
       sh(_patternvar.stellaident_);
       render(")");
    }
  }

  private static void sh(ListPattern foo)
  {
     for (Iterator<Pattern> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(LabelledPattern foo)
  {
    if (foo instanceof ALabelledPattern)
    {
       ALabelledPattern _alabelledpattern = (ALabelledPattern) foo;
       render("(");
       render("ALabelledPattern");
       sh(_alabelledpattern.stellaident_);
       sh(_alabelledpattern.pattern_);
       render(")");
    }
  }

  private static void sh(ListLabelledPattern foo)
  {
     for (Iterator<LabelledPattern> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(Binding foo)
  {
    if (foo instanceof ABinding)
    {
       ABinding _abinding = (ABinding) foo;
       render("(");
       render("ABinding");
       sh(_abinding.stellaident_);
       sh(_abinding.expr_);
       render(")");
    }
  }

  private static void sh(ListBinding foo)
  {
     for (Iterator<Binding> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(Expr foo)
  {
    if (foo instanceof Sequence)
    {
       Sequence _sequence = (Sequence) foo;
       render("(");
       render("Sequence");
       sh(_sequence.expr_1);
       sh(_sequence.expr_2);
       render(")");
    }
    if (foo instanceof Let)
    {
       Let _let = (Let) foo;
       render("(");
       render("Let");
       render("[");
       sh(_let.listpatternbinding_);
       render("]");
       sh(_let.expr_);
       render(")");
    }
    if (foo instanceof LetRec)
    {
       LetRec _letrec = (LetRec) foo;
       render("(");
       render("LetRec");
       render("[");
       sh(_letrec.listpatternbinding_);
       render("]");
       sh(_letrec.expr_);
       render(")");
    }
    if (foo instanceof TypeAbstraction)
    {
       TypeAbstraction _typeabstraction = (TypeAbstraction) foo;
       render("(");
       render("TypeAbstraction");
       render("[");
       sh(_typeabstraction.liststellaident_);
       render("]");
       sh(_typeabstraction.expr_);
       render(")");
    }
    if (foo instanceof Assign)
    {
       Assign _assign = (Assign) foo;
       render("(");
       render("Assign");
       sh(_assign.expr_1);
       sh(_assign.expr_2);
       render(")");
    }
    if (foo instanceof If)
    {
       If _if = (If) foo;
       render("(");
       render("If");
       sh(_if.expr_1);
       sh(_if.expr_2);
       sh(_if.expr_3);
       render(")");
    }
    if (foo instanceof LessThan)
    {
       LessThan _lessthan = (LessThan) foo;
       render("(");
       render("LessThan");
       sh(_lessthan.expr_1);
       sh(_lessthan.expr_2);
       render(")");
    }
    if (foo instanceof LessThanOrEqual)
    {
       LessThanOrEqual _lessthanorequal = (LessThanOrEqual) foo;
       render("(");
       render("LessThanOrEqual");
       sh(_lessthanorequal.expr_1);
       sh(_lessthanorequal.expr_2);
       render(")");
    }
    if (foo instanceof GreaterThan)
    {
       GreaterThan _greaterthan = (GreaterThan) foo;
       render("(");
       render("GreaterThan");
       sh(_greaterthan.expr_1);
       sh(_greaterthan.expr_2);
       render(")");
    }
    if (foo instanceof GreaterThanOrEqual)
    {
       GreaterThanOrEqual _greaterthanorequal = (GreaterThanOrEqual) foo;
       render("(");
       render("GreaterThanOrEqual");
       sh(_greaterthanorequal.expr_1);
       sh(_greaterthanorequal.expr_2);
       render(")");
    }
    if (foo instanceof Equal)
    {
       Equal _equal = (Equal) foo;
       render("(");
       render("Equal");
       sh(_equal.expr_1);
       sh(_equal.expr_2);
       render(")");
    }
    if (foo instanceof NotEqual)
    {
       NotEqual _notequal = (NotEqual) foo;
       render("(");
       render("NotEqual");
       sh(_notequal.expr_1);
       sh(_notequal.expr_2);
       render(")");
    }
    if (foo instanceof TypeAsc)
    {
       TypeAsc _typeasc = (TypeAsc) foo;
       render("(");
       render("TypeAsc");
       sh(_typeasc.expr_);
       sh(_typeasc.type_);
       render(")");
    }
    if (foo instanceof TypeCast)
    {
       TypeCast _typecast = (TypeCast) foo;
       render("(");
       render("TypeCast");
       sh(_typecast.expr_);
       sh(_typecast.type_);
       render(")");
    }
    if (foo instanceof Abstraction)
    {
       Abstraction _abstraction = (Abstraction) foo;
       render("(");
       render("Abstraction");
       render("[");
       sh(_abstraction.listparamdecl_);
       render("]");
       sh(_abstraction.expr_);
       render(")");
    }
    if (foo instanceof Variant)
    {
       Variant _variant = (Variant) foo;
       render("(");
       render("Variant");
       sh(_variant.stellaident_);
       sh(_variant.exprdata_);
       render(")");
    }
    if (foo instanceof Match)
    {
       Match _match = (Match) foo;
       render("(");
       render("Match");
       sh(_match.expr_);
       render("[");
       sh(_match.listmatchcase_);
       render("]");
       render(")");
    }
    if (foo instanceof List)
    {
       List _list = (List) foo;
       render("(");
       render("List");
       render("[");
       sh(_list.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof Add)
    {
       Add _add = (Add) foo;
       render("(");
       render("Add");
       sh(_add.expr_1);
       sh(_add.expr_2);
       render(")");
    }
    if (foo instanceof Subtract)
    {
       Subtract _subtract = (Subtract) foo;
       render("(");
       render("Subtract");
       sh(_subtract.expr_1);
       sh(_subtract.expr_2);
       render(")");
    }
    if (foo instanceof LogicOr)
    {
       LogicOr _logicor = (LogicOr) foo;
       render("(");
       render("LogicOr");
       sh(_logicor.expr_1);
       sh(_logicor.expr_2);
       render(")");
    }
    if (foo instanceof Multiply)
    {
       Multiply _multiply = (Multiply) foo;
       render("(");
       render("Multiply");
       sh(_multiply.expr_1);
       sh(_multiply.expr_2);
       render(")");
    }
    if (foo instanceof Divide)
    {
       Divide _divide = (Divide) foo;
       render("(");
       render("Divide");
       sh(_divide.expr_1);
       sh(_divide.expr_2);
       render(")");
    }
    if (foo instanceof LogicAnd)
    {
       LogicAnd _logicand = (LogicAnd) foo;
       render("(");
       render("LogicAnd");
       sh(_logicand.expr_1);
       sh(_logicand.expr_2);
       render(")");
    }
    if (foo instanceof Ref)
    {
       Ref _ref = (Ref) foo;
       render("(");
       render("Ref");
       sh(_ref.expr_);
       render(")");
    }
    if (foo instanceof Deref)
    {
       Deref _deref = (Deref) foo;
       render("(");
       render("Deref");
       sh(_deref.expr_);
       render(")");
    }
    if (foo instanceof Application)
    {
       Application _application = (Application) foo;
       render("(");
       render("Application");
       sh(_application.expr_);
       render("[");
       sh(_application.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof TypeApplication)
    {
       TypeApplication _typeapplication = (TypeApplication) foo;
       render("(");
       render("TypeApplication");
       sh(_typeapplication.expr_);
       render("[");
       sh(_typeapplication.listtype_);
       render("]");
       render(")");
    }
    if (foo instanceof DotRecord)
    {
       DotRecord _dotrecord = (DotRecord) foo;
       render("(");
       render("DotRecord");
       sh(_dotrecord.expr_);
       sh(_dotrecord.stellaident_);
       render(")");
    }
    if (foo instanceof DotTuple)
    {
       DotTuple _dottuple = (DotTuple) foo;
       render("(");
       render("DotTuple");
       sh(_dottuple.expr_);
       sh(_dottuple.integer_);
       render(")");
    }
    if (foo instanceof Tuple)
    {
       Tuple _tuple = (Tuple) foo;
       render("(");
       render("Tuple");
       render("[");
       sh(_tuple.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof Record)
    {
       Record _record = (Record) foo;
       render("(");
       render("Record");
       render("[");
       sh(_record.listbinding_);
       render("]");
       render(")");
    }
    if (foo instanceof ConsList)
    {
       ConsList _conslist = (ConsList) foo;
       render("(");
       render("ConsList");
       sh(_conslist.expr_1);
       sh(_conslist.expr_2);
       render(")");
    }
    if (foo instanceof Head)
    {
       Head _head = (Head) foo;
       render("(");
       render("Head");
       sh(_head.expr_);
       render(")");
    }
    if (foo instanceof IsEmpty)
    {
       IsEmpty _isempty = (IsEmpty) foo;
       render("(");
       render("IsEmpty");
       sh(_isempty.expr_);
       render(")");
    }
    if (foo instanceof Tail)
    {
       Tail _tail = (Tail) foo;
       render("(");
       render("Tail");
       sh(_tail.expr_);
       render(")");
    }
    if (foo instanceof Panic)
    {
       Panic _panic = (Panic) foo;
       render("Panic");
    }
    if (foo instanceof Throw)
    {
       Throw _throw = (Throw) foo;
       render("(");
       render("Throw");
       sh(_throw.expr_);
       render(")");
    }
    if (foo instanceof TryCatch)
    {
       TryCatch _trycatch = (TryCatch) foo;
       render("(");
       render("TryCatch");
       sh(_trycatch.expr_1);
       sh(_trycatch.pattern_);
       sh(_trycatch.expr_2);
       render(")");
    }
    if (foo instanceof TryWith)
    {
       TryWith _trywith = (TryWith) foo;
       render("(");
       render("TryWith");
       sh(_trywith.expr_1);
       sh(_trywith.expr_2);
       render(")");
    }
    if (foo instanceof TryCastAs)
    {
       TryCastAs _trycastas = (TryCastAs) foo;
       render("(");
       render("TryCastAs");
       sh(_trycastas.expr_1);
       sh(_trycastas.type_);
       sh(_trycastas.pattern_);
       sh(_trycastas.expr_2);
       sh(_trycastas.expr_3);
       render(")");
    }
    if (foo instanceof Inl)
    {
       Inl _inl = (Inl) foo;
       render("(");
       render("Inl");
       sh(_inl.expr_);
       render(")");
    }
    if (foo instanceof Inr)
    {
       Inr _inr = (Inr) foo;
       render("(");
       render("Inr");
       sh(_inr.expr_);
       render(")");
    }
    if (foo instanceof Succ)
    {
       Succ _succ = (Succ) foo;
       render("(");
       render("Succ");
       sh(_succ.expr_);
       render(")");
    }
    if (foo instanceof LogicNot)
    {
       LogicNot _logicnot = (LogicNot) foo;
       render("(");
       render("LogicNot");
       sh(_logicnot.expr_);
       render(")");
    }
    if (foo instanceof Pred)
    {
       Pred _pred = (Pred) foo;
       render("(");
       render("Pred");
       sh(_pred.expr_);
       render(")");
    }
    if (foo instanceof IsZero)
    {
       IsZero _iszero = (IsZero) foo;
       render("(");
       render("IsZero");
       sh(_iszero.expr_);
       render(")");
    }
    if (foo instanceof Fix)
    {
       Fix _fix = (Fix) foo;
       render("(");
       render("Fix");
       sh(_fix.expr_);
       render(")");
    }
    if (foo instanceof NatRec)
    {
       NatRec _natrec = (NatRec) foo;
       render("(");
       render("NatRec");
       sh(_natrec.expr_1);
       sh(_natrec.expr_2);
       sh(_natrec.expr_3);
       render(")");
    }
    if (foo instanceof Fold)
    {
       Fold _fold = (Fold) foo;
       render("(");
       render("Fold");
       sh(_fold.type_);
       sh(_fold.expr_);
       render(")");
    }
    if (foo instanceof Unfold)
    {
       Unfold _unfold = (Unfold) foo;
       render("(");
       render("Unfold");
       sh(_unfold.type_);
       sh(_unfold.expr_);
       render(")");
    }
    if (foo instanceof ConstTrue)
    {
       ConstTrue _consttrue = (ConstTrue) foo;
       render("ConstTrue");
    }
    if (foo instanceof ConstFalse)
    {
       ConstFalse _constfalse = (ConstFalse) foo;
       render("ConstFalse");
    }
    if (foo instanceof ConstUnit)
    {
       ConstUnit _constunit = (ConstUnit) foo;
       render("ConstUnit");
    }
    if (foo instanceof ConstInt)
    {
       ConstInt _constint = (ConstInt) foo;
       render("(");
       render("ConstInt");
       sh(_constint.integer_);
       render(")");
    }
    if (foo instanceof ConstMemory)
    {
       ConstMemory _constmemory = (ConstMemory) foo;
       render("(");
       render("ConstMemory");
       sh(_constmemory.memoryaddress_);
       render(")");
    }
    if (foo instanceof Var)
    {
       Var _var = (Var) foo;
       render("(");
       render("Var");
       sh(_var.stellaident_);
       render(")");
    }
  }

  private static void sh(ListExpr foo)
  {
     for (Iterator<Expr> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(PatternBinding foo)
  {
    if (foo instanceof APatternBinding)
    {
       APatternBinding _apatternbinding = (APatternBinding) foo;
       render("(");
       render("APatternBinding");
       sh(_apatternbinding.pattern_);
       sh(_apatternbinding.expr_);
       render(")");
    }
  }

  private static void sh(ListPatternBinding foo)
  {
     for (Iterator<PatternBinding> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(VariantFieldType foo)
  {
    if (foo instanceof AVariantFieldType)
    {
       AVariantFieldType _avariantfieldtype = (AVariantFieldType) foo;
       render("(");
       render("AVariantFieldType");
       sh(_avariantfieldtype.stellaident_);
       sh(_avariantfieldtype.optionaltyping_);
       render(")");
    }
  }

  private static void sh(ListVariantFieldType foo)
  {
     for (Iterator<VariantFieldType> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(RecordFieldType foo)
  {
    if (foo instanceof ARecordFieldType)
    {
       ARecordFieldType _arecordfieldtype = (ARecordFieldType) foo;
       render("(");
       render("ARecordFieldType");
       sh(_arecordfieldtype.stellaident_);
       sh(_arecordfieldtype.type_);
       render(")");
    }
  }

  private static void sh(ListRecordFieldType foo)
  {
     for (Iterator<RecordFieldType> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(Typing foo)
  {
    if (foo instanceof ATyping)
    {
       ATyping _atyping = (ATyping) foo;
       render("(");
       render("ATyping");
       sh(_atyping.expr_);
       sh(_atyping.type_);
       render(")");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + escape(c.toString()) + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + escape(c.toString()) + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + escape(s) + "\""); }

  public static String escape(String s) {
    if (s == null) return null;
    return s.replace("\\", "\\\\")
            .replace("\t", "\\t")
            .replace("\b", "\\b")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\f", "\\f")
            .replace("\"", "\\\"");
  }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

